import {LANGUAGES,resolveLanguage,localeFor,dirFor,translator} from "./i18n.js";

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE_KEY="warboost_v1_core_state", CLIENT_KEY="warboost_v1_client_id", LANG_KEY="warboost_v12_language";
function uid(){return crypto.randomUUID?.()||`wb-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function clientId(){let id=localStorage.getItem(CLIENT_KEY);if(!id){id=uid();localStorage.setItem(CLIENT_KEY,id)}return id}
function emptyHero(i){return {name:"",level:null,stars:null,power:null,exclusive:null,gear:null}}
function emptySquad(i){return {id:i,name:`Squad ${i}`,power:null,updated_at:null,heroes:[1,2,3,4,5].map(emptyHero)}}
function initialState(){return {version:"2.2.0",player_id:clientId(),updated_at:null,player:{name:"",server_id:"",hq_level:null,power_m:null,coordinates:null,role:"R1"},exclusive_weapons:[],drone:{level:null,power_m:null,updated_at:null},shop:{store_type:"",currency:"",currency_balance:null,vip_level:null,vip_days_remaining:null,offers:[],updated_at:null},squads:[1,2,3,4].map(emptySquad),alliance:{id:null,tag:"",name:"",role:"R1",invite_code:"",members:[],updated_at:null},vs:{week:null,day:null,our_alliance:"",opponent:"",our_score:null,their_score:null,updated_at:null},season:{name:"",number:null,day:null,total_days:null,profession:"",progress_pct:0,resistance:null,updated_at:null},sync:{provider:"warboost-local",provider_kind:"local",access_status:"pending",capabilities:[],status:"local",last_sync:null,last_error:null,auto_ready:true,last_scan:null,official_last_sync:null,public_last_sync:null,sources:{official:false,public:false,scan:false,alliance:false}}}}
function canonicalStoredHeroName(v){const s=String(v||"").trim();if(!s)return s;if(/^(?:hero|héros|heroe|héroe|held|英雄|بطل)\s*\d+$/i.test(s))return "";if(/^(?:schuyler|shuyler|skyler)$/i.test(s))return "Skyler";if(/^morriss?on$/i.test(s))return "Morrisson";return s}
function mergeExclusiveWeapons(baseList,incomingList){
  const out=Array.isArray(baseList)?baseList.map(x=>({...x,hero_name:canonicalStoredHeroName(x?.hero_name)})):[];
  if(!Array.isArray(incomingList))return out;
  const keyOf=x=>String(canonicalStoredHeroName(x?.hero_name)||x?.weapon_name||"").trim().toLowerCase();
  for(const item of incomingList){
    if(!item||typeof item!=="object")continue;
    const key=keyOf(item);
    if(!key)continue;
    const idx=out.findIndex(x=>keyOf(x)===key);
    const normalized={...item,hero_name:canonicalStoredHeroName(item?.hero_name)};
    if(idx>=0)out[idx]={...out[idx],...normalized};
    else out.push(normalized);
  }
  return out.slice(0,24);
}
function mergeState(base,incoming){if(!incoming||typeof incoming!=="object")return base;const out={...base,...incoming};out.player={...base.player,...incoming.player};out.drone={...base.drone,...incoming.drone};out.shop={...base.shop,...incoming.shop,offers:Array.isArray(incoming.shop?.offers)?incoming.shop.offers:(base.shop?.offers||[])};out.alliance={...base.alliance,...incoming.alliance};out.vs={...base.vs,...incoming.vs};out.season={...base.season,...incoming.season};out.exclusive_weapons=mergeExclusiveWeapons(base.exclusive_weapons,incoming.exclusive_weapons);out.sync={...base.sync,...incoming.sync,sources:{...base.sync.sources,...incoming.sync?.sources}};out.squads=Array.from({length:4},(_,i)=>{const src=incoming.squads?.[i]||{};return {...base.squads[i],...src,id:i+1,name:`Squad ${i+1}`,heroes:Array.from({length:5},(_,j)=>{const h={...base.squads[i].heroes[j],...(src.heroes?.[j]||{})};h.name=canonicalStoredHeroName(h.name);return h})}});out.version="1.6.3";return out}
function loadState(){try{const raw=localStorage.getItem(STORE_KEY);return raw?mergeState(initialState(),JSON.parse(raw)):initialState()}catch{return initialState()}}
let state=loadState(),serverNow=new Date(),pushTimer=null,suppressPush=false,cloud=null,cloudSession=null,proState={active:false,status:"free",configured:false,plan:null},scanImageData=null;
const HERO_CATALOG=["Adam","Ambolt","Blaz","Cage","Carlie","DVA","Elsa","Farhad","Fiona","Gump","Kane","Kimberly","Loki","Lucius","Marshall","Mason","Maxwell","McGregor","Monica","Morrisson","Murphy","Richard","Sarah","Scarlett","Skyler","Stetmann","Swift","Tesla","Venom","Violet","Williams"];
let pendingHeroSquadId=null,pendingHeroSuggestions=[];
function clearScanImage(){scanImageData=null;const f=$("#scanFile"),p=$("#scanPreview");if(f)f.value="";if(p)p.classList.add("hidden")}
function heroConfirmOptions(selected){return [`<option value="">${esc(t("hero_choose"))}</option>`].concat(HERO_CATALOG.map(n=>`<option value="${esc(n)}"${n===selected?" selected":""}>${esc(n)}</option>`)).join("")}
function openHeroConfirmation(squadId,suggestions=[]){pendingHeroSquadId=Number(squadId)||null;pendingHeroSuggestions=Array.from({length:5},(_,i)=>String(suggestions?.[i]||"").trim());const panel=$("#heroConfirmPanel"),rows=$("#heroConfirmRows");if(!panel||!rows||!pendingHeroSquadId)return false;const sq=state.squads[pendingHeroSquadId-1];if(!sq)return false;rows.innerHTML=(sq.heroes||[]).slice(0,5).map((h,i)=>{const saved=isGenericHeroName(h?.name)?"":h.name;const suggested=pendingHeroSuggestions[i]&&!isGenericHeroName(pendingHeroSuggestions[i])?pendingHeroSuggestions[i]:"";const current=suggested||saved;return `<div class="heroConfirmRow"><span>${i+1}</span><select data-hero-slot="${i}">${heroConfirmOptions(current)}</select></div>`}).join("");$("#heroConfirmTitle").textContent=t("hero_confirm_title",{squad:pendingHeroSquadId});panel.classList.remove("hidden");return true;}
function startHeroConfirmation(squadId,suggestions=[]){const id=Number(squadId);if(!Number.isInteger(id)||id<1||id>4)return;openDrawer("scan");renderScanTypeOptions();const type=$("#scanType");if(type)type.value=`squad${id}`;const st=$("#scanStatus");if(st){st.className="notice warn";st.textContent=t("hero_confirm_needed")}const opened=openHeroConfirmation(id,suggestions);if(!opened)return;const drawer=$("#scanDrawer"),panel=$("#heroConfirmPanel");if(drawer)drawer.scrollTop=0;requestAnimationFrame(()=>requestAnimationFrame(()=>{try{panel?.scrollIntoView({behavior:"smooth",block:"center"})}catch{if(drawer)drawer.scrollTop=Math.max(0,(panel?.offsetTop||0)-24)}}));}
function closeHeroConfirmation(clearImage=true){pendingHeroSquadId=null;pendingHeroSuggestions=[];$("#heroConfirmPanel")?.classList.add("hidden");if(clearImage)clearScanImage()}
async function saveHeroConfirmation(){if(!pendingHeroSquadId)return;const selects=[...document.querySelectorAll("#heroConfirmRows select[data-hero-slot]")],values=selects.map(x=>String(x.value||"").trim());const st=$("#scanStatus"),btn=$("#saveHeroNamesBtn");if(values.length!==5||values.some(v=>!v)){st.className="notice warn";st.textContent=t("hero_all_required");return}if(new Set(values).size!==values.length){st.className="notice warn";st.textContent=t("hero_duplicate");return}const id=pendingHeroSquadId,next=JSON.parse(JSON.stringify(state)),sq=next.squads?.[id-1];if(!sq){st.className="notice warn";st.textContent=t("hero_save_failed");return}values.forEach((value,i)=>{if(!sq.heroes[i])sq.heroes[i]=emptyHero(i+1);sq.heroes[i].name=canonicalStoredHeroName(value)});const now=new Date().toISOString();sq.updated_at=now;next.updated_at=now;next.version="1.6.3";if(btn){btn.disabled=true;btn.textContent=t("syncing")}st.className="notice";st.textContent=t("hero_saving");try{let persisted=next;if(cloudSession?.access_token){const r=await fetch("/api/state",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({state:next})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||"hero_save_failed");if(j?.state)persisted=mergeState(next,j.state)}state=persisted;state.version="1.6.3";localStorage.setItem(STORE_KEY,JSON.stringify(state));render();st.className="notice";st.textContent=t("hero_confirm_saved");closeHeroConfirmation(true)}catch{st.className="notice warn";st.textContent=t("hero_save_failed");if(btn){btn.disabled=false;btn.textContent=t("hero_save")}}}
async function skipHeroConfirmation(){if(!pendingHeroSquadId){closeHeroConfirmation(true);return}const id=pendingHeroSquadId,next=JSON.parse(JSON.stringify(state)),sq=next.squads?.[id-1],st=$("#scanStatus"),btn=$("#skipHeroNamesBtn");if(sq?.heroes)for(const h of sq.heroes){if(isGenericHeroName(h?.name))h.name=""}next.version="1.6.3";if(btn)btn.disabled=true;st.className="notice";st.textContent=t("syncing");try{let persisted=next;if(cloudSession?.access_token){const r=await fetch("/api/state",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({state:next})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||"hero_save_failed");if(j?.state)persisted=mergeState(next,j.state)}state=persisted;state.version="1.6.3";localStorage.setItem(STORE_KEY,JSON.stringify(state));render();st.className="notice";st.textContent=t("hero_confirm_skipped");closeHeroConfirmation(true)}catch{st.className="notice warn";st.textContent=t("hero_save_failed");if(btn)btn.disabled=false}}

function inlineHeroConfirmationHtml(sq,squadId){const rows=Array.from({length:5},(_,i)=>{const h=sq.heroes?.[i]||emptyHero(i+1),saved=isGenericHeroName(h?.name)?"":canonicalStoredHeroName(h.name);return `<div class="inlineHeroConfirmRow"><span class="inlineHeroSlot">${i+1}</span><select class="fieldSelect inlineHeroSelect" data-inline-hero-slot="${i}">${heroConfirmOptions(saved)}</select></div>`}).join("");return `<div class="inlineHeroConfirm" data-inline-confirm="${squadId}"><div class="inlineHeroConfirmHead"><div><b>${esc(t("hero_confirm_title",{squad:squadId}))}</b><small>${esc(t("hero_confirm_help"))}</small></div><span class="pill">${esc(t("hero_confirm_badge"))}</span></div><div class="inlineHeroConfirmRows">${rows}</div><div class="notice warn hidden" data-inline-hero-status></div><button class="primaryAction inlineHeroSaveBtn" type="button" data-inline-hero-save="${squadId}">${esc(t("hero_save"))}</button></div>`}
async function saveInlineHeroNames(squadId,container,button=null){
  const id=Number(squadId);
  if(!Number.isInteger(id)||id<1||id>4||!container)return;
  const selects=[...container.querySelectorAll("select[data-inline-hero-slot]")];
  const values=selects.map(x=>String(x.value||"").trim());
  const status=container.querySelector("[data-inline-hero-status]");
  const show=(key,warn=true)=>{if(status){status.className=`notice${warn?" warn":""}`;status.textContent=t(key)}};
  if(values.length!==5||values.some(v=>!v))return show("hero_all_required");
  if(new Set(values).size!==values.length)return show("hero_duplicate");
  const next=JSON.parse(JSON.stringify(state));
  const sq=next.squads?.[id-1];
  if(!sq)return show("hero_save_failed");
  values.forEach((value,i)=>{if(!sq.heroes[i])sq.heroes[i]=emptyHero(i+1);sq.heroes[i].name=canonicalStoredHeroName(value)});
  const now=new Date().toISOString();
  sq.updated_at=now;next.updated_at=now;next.version="1.6.3";
  if(button){button.disabled=true;button.textContent=t("syncing")}
  show("hero_saving",false);
  try{
    let persisted=next;
    if(cloudSession?.access_token){
      const r=await fetch("/api/state",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({state:next})});
      const j=await r.json().catch(()=>({}));
      if(!r.ok)throw new Error(j.message||"hero_save_failed");
      if(j?.state)persisted=mergeState(next,j.state);
    }
    state=persisted;state.version="1.6.3";
    localStorage.setItem(STORE_KEY,JSON.stringify(state));
    render();
    requestAnimationFrame(()=>{const squads=[...document.querySelectorAll("#squadList .squad")];squads[id-1]?.classList.add("open")});
  }catch{
    show("hero_save_failed");
    if(button){button.disabled=false;button.textContent=t("hero_save")}
  }
}

let languageChoice=localStorage.getItem(LANG_KEY)||"auto",lang=resolveLanguage(languageChoice),locale=localeFor(lang),t=translator(lang);
function authHeaders(extra={}){return {...extra,...(cloudSession?.access_token?{authorization:`Bearer ${cloudSession.access_token}`}:{})}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function tpl(key,vars={}){return t(key,vars)}
function fmtPower(v){if(v===null||v===undefined||v==="")return "—";const n=Number(v);if(!Number.isFinite(n))return String(v);return `${new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(n)} M`}
function fmtAgo(iso){if(!iso)return t("never");const d=Math.max(0,Date.now()-new Date(iso).getTime());if(d<60e3)return t("just_now");if(d<3600e3)return `${Math.floor(d/60e3)} ${t("minutes")}`;if(d<86400e3)return `${Math.floor(d/3600e3)} ${t("hours")}`;return `${Math.floor(d/86400e3)} ${t("days")}`}
function isoWeek(d){const x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}
function vsDayFromServer(d){const day=d.getUTCDay();return day===0?6:day}
function renderScanTypeOptions(){const sel=$("#scanType");if(!sel)return;const current=sel.value||"profile";const opts=[["profile",t("scan_profile")],["squad1",`${t("squad")} 1`],["squad2",`${t("squad")} 2`],["squad3",`${t("squad")} 3`],["squad4",`${t("squad")} 4`],["drone",t("scan_drone")],["exclusive",t("scan_exclusive")],["shop",t("scan_shop")],["vs",t("scan_vs")],["season",t("scan_season")]];sel.innerHTML=opts.map(([v,label])=>`<option value="${v}">${label}</option>`).join("");sel.value=opts.some(([v])=>v===current)?current:"profile"}
function applyLanguage(){lang=resolveLanguage(languageChoice);locale=localeFor(lang);t=translator(lang);document.documentElement.lang=lang;document.documentElement.dir=dirFor(lang);$$('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});$$('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAria)));const sel=$("#languageSelect");if(sel){sel.innerHTML=LANGUAGES.map(([v,label])=>`<option value="${v}">${label}</option>`).join("");sel.value=languageChoice}renderScanTypeOptions();renderClock();render();renderAuth();renderPro();$("#proPriorityPanel")?.classList.add("hidden");$("#playerSyncInfo")?.classList.remove("hidden")}
function saveState(){state.updated_at=new Date().toISOString();state.version="1.6.3";localStorage.setItem(STORE_KEY,JSON.stringify(state));render();if(!suppressPush)scheduleServerSave()}
function scheduleServerSave(){clearTimeout(pushTimer);pushTimer=setTimeout(pushServerState,700)}

async function initCloudAuth(){try{const r=await fetch("/api/cloud-config",{cache:"no-store"});const cfg=await r.json();if(!r.ok||!cfg.configured||!window.supabase?.createClient)throw new Error();cloud=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await cloud.auth.getSession();await applySession(data?.session||null);cloud.auth.onAuthStateChange((_event,session)=>applySession(session||null))}catch{renderAuth()}}
async function applySession(session){cloudSession=session||null;if(cloudSession?.user?.id){const oldId=state.player_id;state.player_id=cloudSession.user.id;if(oldId!==state.player_id)localStorage.setItem(STORE_KEY,JSON.stringify(state));await pullServerState();await refreshPro()}else{proState={active:false,status:"free",configured:false,plan:null}}renderAuth();renderPro()}
function renderAuth(){const logged=Boolean(cloudSession?.user);$("#authLoggedOut")?.classList.toggle("hidden",logged);$("#authLoggedIn")?.classList.toggle("hidden",!logged);if($("#authPill"))$("#authPill").textContent=logged?t("connected"):(cloud?t("ready"):t("local"));if(logged&&$("#authIdentity"))$("#authIdentity").textContent=`WarBoost · ${cloudSession.user.email||""}`;renderPro()}
function authMessage(text,ok=false){const el=$("#authMessage");if(!el)return;el.className=`notice${ok?"":" warn"}`;el.textContent=text}
async function pushServerState(){if(!cloudSession?.access_token)return;try{const r=await fetch("/api/state",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({state})});if(!r.ok)return;const j=await r.json().catch(()=>({}));if(j?.updated_at){state.sync.last_sync=state.sync.last_sync||j.updated_at;localStorage.setItem(STORE_KEY,JSON.stringify(state))}}catch{}}
async function pullServerState(){if(!cloudSession?.access_token)return;try{const r=await fetch("/api/state",{cache:"no-store",headers:authHeaders()});if(!r.ok)return;const j=await r.json();if(j?.state){suppressPush=true;state=mergeState(state,j.state);localStorage.setItem(STORE_KEY,JSON.stringify(state));render();suppressPush=false}}catch{}}

async function refreshServerTime(){try{const r=await fetch("/api/time",{cache:"no-store"});if(!r.ok)throw new Error();const j=await r.json();serverNow=new Date(j.now);state.vs.week=j.iso_week;state.vs.day=j.vs_day;$("#syncPill").className="syncState good";$("#syncPill").textContent=t("server_ok")}catch{serverNow=new Date();state.vs.week=isoWeek(serverNow);state.vs.day=vsDayFromServer(serverNow);$("#syncPill").className="syncState";$("#syncPill").textContent=t("local_time")}renderClock();render()}
function renderClock(){const d=serverNow;const clock=$("#serverClock"),day=$("#serverDay");if(clock)clock.textContent=d.toLocaleTimeString(locale,{hour:"2-digit",minute:"2-digit",second:"2-digit"});if(day)day.textContent=`${d.toLocaleDateString(locale,{weekday:"long",day:"2-digit",month:"short"})} · ${t("week")} ${isoWeek(d)}`}
setInterval(()=>{serverNow=new Date(serverNow.getTime()+1000);renderClock()},1000);setInterval(refreshServerTime,5*60*1000);

function render(){const p=state.player,a=state.alliance,v=state.vs,s=state.season,d=state.drone||{};if(!$("#playerMeta"))return;$("#playerMeta").textContent=p.name?(p.hq_level?`${t("hq")} ${p.hq_level}`:t("connected")):t("to_connect");$("#allianceMeta").textContent=a.tag||"—";$("#vsMeta").textContent=`${t("week")} ${v.week||isoWeek(serverNow)}`;$("#seasonMeta").textContent=s.name||(s.number?`S${s.number}`:t("to_fill"));$("#pName").textContent=p.name||"—";$("#pHq").textContent=p.hq_level?`${t("hq")} ${p.hq_level}`:"—";$("#pPower").textContent=fmtPower(p.power_m);$("#pDrone").textContent=d.level?`${t("level")}${d.level}${d.power_m?` · ${fmtPower(d.power_m)}`:""}`:"—";renderSquads();renderExclusiveWeapons();$("#aTag").textContent=a.tag||"—";$("#aCount").textContent=String(a.members?.length||0);$("#aRole").textContent=a.role||p.role||"R1";$("#inviteCode").textContent=ensureInviteCode();$("#rosterFresh").textContent=a.updated_at?`${t("update")} ${fmtAgo(a.updated_at)}`:t("sync_needed");renderMembers();$("#vsWeekTitle").textContent=t("vs_week",{week:v.week||isoWeek(serverNow)});$("#vsDayPill").textContent=t("day_n",{day:v.day||vsDayFromServer(serverNow)});$("#vsUs").textContent=v.our_alliance||a.tag||t("your_alliance");$("#vsThem").textContent=v.opponent||t("unknown_opponent");$("#vsUsScore").textContent=v.our_score??"—";$("#vsThemScore").textContent=v.their_score??"—";renderVsTimeline();$("#sName").textContent=s.name||(s.number?`S${s.number}`:"—");$("#sDay").textContent=s.day||"—";$("#sProfession").textContent=s.profession||"—";const pct=Math.max(0,Math.min(100,Number(s.progress_pct||0)));$("#seasonProgressBar").style.width=`${pct}%`;$("#seasonProgressLabel").textContent=`${pct}%`;$("#seasonStatus").textContent=s.updated_at?`${t("last_update",{ago:fmtAgo(s.updated_at)})} · ${s.resistance??"—"}`:t("season_wait");renderAdvice();renderAccountFields();renderProvider()}
function squadHasSavedData(sq){return Boolean(sq?.updated_at||Number(sq?.power)>0||(sq?.heroes||[]).some(h=>h?.name||h?.level||h?.stars||h?.power||h?.exclusive||h?.gear))}
function isGenericHeroName(v){const s=String(v||"").trim();return !s||/^(?:hero|héros|heroe|héroe|held|英雄|英雄|بطل)\s*\d+$/i.test(s)}
function formatGear(raw){const s=String(raw||"").trim();if(!s)return "";const localizeRarities=value=>String(value||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean).map(x=>{const k=`rarity_${x}`;return t(k)===k?x:t(k)}).join("/");let m=s.match(/^count=(\d+);level=(\d+);rarity=([a-z,]+)$/i);if(!m)m=s.match(/^(\d+)\s+gear items?,\s*Lv\.?\s*(\d+),\s*([a-z]+)\s+rarity$/i);if(m)return `${m[1]} ${t("gear_items")} · ${t("level")}${m[2]} · ${t("rarity")} ${localizeRarities(m[3])}`;const ml=s.match(/^count=(\d+);levels=([0-9,]+);rarity=([a-z,]+)$/i);if(ml){const levels=ml[2].split(",").map(x=>Number(x)).filter(Number.isFinite),levelText=levels.map(x=>`${t("level")}${x}`).join("/");return `${ml[1]} ${t("gear_items")} · ${levelText} · ${t("rarity")} ${localizeRarities(ml[3])}`}const lv=s.match(/^Lv\.?\s*(\d+)$/i);if(lv)return `${t("level")}${lv[1]}`;return s}
function weaponStatsLine(w){if(!w)return "";const bits=[w.hero_hp_bonus!=null?`${t("exclusive_hp")} +${new Intl.NumberFormat(locale).format(Number(w.hero_hp_bonus))}`:null,w.hero_atk_bonus!=null?`${t("exclusive_atk")} +${new Intl.NumberFormat(locale).format(Number(w.hero_atk_bonus))}`:null,w.hero_def_bonus!=null?`${t("exclusive_def")} +${new Intl.NumberFormat(locale).format(Number(w.hero_def_bonus))}`:null,w.all_damage_resistance_pct!=null?`${t("exclusive_resistance")} ${new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(Number(w.all_damage_resistance_pct))}%`:null,w.max_skill_level!=null?`${t("exclusive_skill_cap")} ${new Intl.NumberFormat(locale,{maximumFractionDigits:0}).format(Number(w.max_skill_level))}`:null].filter(Boolean);return bits.join(" · ")}
function heroDetailLine(h,heroName){const bits=[h.level?`${t("level")}${h.level}`:`${t("level")}—`,h.stars?`${h.stars}★`:"★—"];const w=weaponForHero(heroName);if(w){const weaponTitle=w.weapon_name||t("exclusive_weapon");bits.push(`${weaponTitle}${w.level?` ${t("level")}${w.level}`:""}`);if(w.power)bits.push(`${t("exclusive_power")} ${fmtWeaponPower(w.power)}`)}else if(h.exclusive){bits.push(`${t("exclusive_short")} ${h.exclusive}`)}if(h.gear)bits.push(formatGear(h.gear));return {main:bits.join(" · "),stats:weaponStatsLine(w)}}
function renderSquads(){const box=$("#squadList");if(!box)return;box.innerHTML="";state.squads.forEach((sq,i)=>{const el=document.createElement("div");el.className="squad";const name=`${t("squad")} ${i+1}`;const optional4=i===3&&!squadHasSavedData(sq);const freshness=optional4?t("optional_squad4"):(sq.updated_at?`${t("update")} ${fmtAgo(sq.updated_at)}`:t("not_synced"));const needsHeroConfirm=!optional4&&(sq.heroes||[]).some(h=>isGenericHeroName(h?.name))&&squadHasSavedData(sq);el.innerHTML=`<button class="squadHead"><span class="squadNo">${i+1}</span><span class="squadName"><b>${esc(name)}</b><small>${esc(freshness)}</small></span><span class="squadPower">${fmtPower(sq.power)}</span><span class="chev">⌄</span></button><div class="squadBody">${(sq.heroes||[]).map((h,j)=>{const hn=isGenericHeroName(h.name)?`${t("hero")} ${j+1} · ${t("hero_unconfirmed")}`:h.name;const detail=heroDetailLine(h,hn);return `<div class="heroRow"><div class="heroAvatar">${j+1}</div><div class="heroInfo"><b>${esc(hn)}</b><small>${esc(detail.main)}</small>${detail.stats?`<span class="heroWeaponStats">${esc(detail.stats)}</span>`:""}</div><div class="heroPwr">${fmtPower(h.power)}</div></div>`}).join("")}${needsHeroConfirm?inlineHeroConfirmationHtml(sq,i+1):""}</div>`;el.querySelector(".squadHead").addEventListener("click",()=>el.classList.toggle("open"));box.appendChild(el)})}

function fmtWeaponPower(v){
  const n=Number(v);if(!Number.isFinite(n))return "—";
  if(n>=1_000_000)return new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(n/1_000_000)+" M";
  return new Intl.NumberFormat(locale,{maximumFractionDigits:0}).format(n);
}
function normalizedName(v){return String(v||"").trim().toLowerCase().replace(/\s+/g," ")}
function weaponForHero(name){
  const n=normalizedName(name);if(!n)return null;
  return (state.exclusive_weapons||[]).find(w=>normalizedName(w.hero_name)===n)||null;
}
function renderExclusiveWeapons(){
  const box=$("#exclusiveWeaponList"),count=$("#exclusiveWeaponCount");if(!box)return;
  const list=(state.exclusive_weapons||[]).filter(w=>w&&(w.hero_name||w.weapon_name||w.level||w.power));
  if(count)count.textContent=String(list.length);
  if(!list.length){
    box.innerHTML=`<div class="exclusiveEmpty">${esc(t("exclusive_empty"))}</div>`;
    return;
  }
  box.innerHTML=list.map(w=>{
    const title=w.weapon_name||t("exclusive_weapon");
    const hero=w.hero_name||t("hero");
    const level=w.level?`${t("level")}${esc(w.level)}`:t("level")+"—";
    const power=w.power?fmtWeaponPower(w.power):"—";
    const stats=[
      w.hero_hp_bonus!=null?`${t("exclusive_hp")} +${new Intl.NumberFormat(locale).format(Number(w.hero_hp_bonus))}`:null,
      w.hero_atk_bonus!=null?`${t("exclusive_atk")} +${new Intl.NumberFormat(locale).format(Number(w.hero_atk_bonus))}`:null,
      w.hero_def_bonus!=null?`${t("exclusive_def")} +${new Intl.NumberFormat(locale).format(Number(w.hero_def_bonus))}`:null,
      w.all_damage_resistance_pct!=null?`${t("exclusive_resistance")} ${new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(Number(w.all_damage_resistance_pct))}%`:null,
      w.max_skill_level!=null?`${t("exclusive_skill_cap")} ${new Intl.NumberFormat(locale,{maximumFractionDigits:0}).format(Number(w.max_skill_level))}`:null
    ].filter(Boolean);
    return `<div class="exclusiveCard"><div class="exclusiveIcon">⚔️</div><div class="exclusiveMain"><b>${esc(hero)} · ${esc(title)}</b><small>${esc(level)} · ${esc(t("exclusive_power"))} ${esc(power)}</small>${stats.length?`<span>${esc(stats.join(" · "))}</span>`:""}</div></div>`;
  }).join("");
}

function aiUiText(){const k=String(lang||"en").toLowerCase();if(k.startsWith("fr"))return {impact:"Impact",roi:"Efficacité ressources",why:"Pourquoi",details:"Voir les détails",evaluated:"options comparées",avoid:"À ne pas améliorer / acheter maintenant",heroes:"héros détectés"};if(k.startsWith("es"))return {impact:"Impacto",roi:"Eficiencia de recursos",why:"Por qué",details:"Ver detalles",evaluated:"opciones comparadas",avoid:"No mejorar / comprar ahora",heroes:"héroes detectados"};if(k.startsWith("de"))return {impact:"Wirkung",roi:"Ressourceneffizienz",why:"Warum",details:"Details anzeigen",evaluated:"Optionen verglichen",avoid:"Jetzt nicht verbessern / kaufen",heroes:"erkannte Helden"};if(k.startsWith("ja"))return {impact:"効果",roi:"資源効率",why:"理由",details:"詳細を見る",evaluated:"件を比較",avoid:"今は強化・購入しない",heroes:"検出英雄"};if(k.startsWith("zh"))return {impact:"影响",roi:"资源效率",why:"原因",details:"查看详情",evaluated:"个方案已比较",avoid:"暂时不要升级/购买",heroes:"已识别英雄"};if(k.startsWith("ar"))return {impact:"الأثر",roi:"كفاءة الموارد",why:"السبب",details:"عرض التفاصيل",evaluated:"خياراً تمت مقارنتها",avoid:"لا تطور / تشترِ الآن",heroes:"أبطال تم اكتشافهم"};return {impact:"Impact",roi:"Resource efficiency",why:"Why",details:"View details",evaluated:"options compared",avoid:"Do not upgrade / buy now",heroes:"heroes detected"}}
function renderProPriority(analysis){
  const ui=aiUiText(),panel=$("#proPriorityPanel"),summary=$("#proPrioritySummary"),list=$("#proPriorityList"),compare=$("#proSquadCompare"),confidence=$("#proConfidence"),note=$("#playerSyncInfo"),shopList=$("#proShopList"),shopSummary=$("#proShopSummary"),shopConfidence=$("#shopConfidence"),shopCatalogPill=$("#shopCatalogPill"),avoid=$("#proAvoidList");
  if(!panel||!analysis)return;
  if(note)note.classList.add("hidden");panel.classList.remove("hidden");
  if(summary){
    const mi=analysis.meta_intelligence,composition=analysis.composition?.label?` · ${analysis.composition.label}`:"";
    summary.textContent=`${analysis.summary||""}${composition}${analysis.candidates_evaluated?` · ${analysis.candidates_evaluated} ${ui.evaluated}`:""}${mi?.source_count?` · AI sources ${mi.source_count} · Meta ${mi.confidence}%`:""}`;
  }
  if(confidence)confidence.textContent=analysis.confidence_label||`${analysis.confidence||0}%`;
  if(list){
    const items=(Array.isArray(analysis.priorities)?analysis.priorities:[]).slice(0,3);
    list.innerHTML=items.length?items.map(x=>`<article class="priorityCard compactDecision"><span class="priorityRank">${esc(x.rank||"•")}</span><div class="priorityMain"><div class="decisionHead"><b>${esc(x.title||"")}${x.target?` · ${esc(x.target)}`:""}</b><span class="decisionMetric">${esc(ui.impact)} : ${esc(x.impact_label||"—")} · ${esc(ui.roi)} : ${esc(x.resource_efficiency_label||x.roi_label||"—")}${Array.isArray(x.evidence_ids)&&x.evidence_ids.length?` · ${x.evidence_ids.length} src`:""}</span></div><strong>${esc(x.action||"")}</strong><details class="decisionDetails"><summary>${esc(ui.why)}</summary><p>${esc(x.reason||"")}</p><small>🆓 ${esc(x.buy_free||"")}</small><small>💎 ${esc(x.buy_paid||"")}</small></details></div></article>`).join(""):`<div class="notice">${esc(analysis.summary||t("player_sync_note"))}</div>`;
  }
  if(avoid){
    const rows=Array.isArray(analysis.avoid_now)?analysis.avoid_now:[];
    avoid.innerHTML=rows.length?`<div class="avoidTitle">⛔ ${esc(ui.avoid)}</div>${rows.map(x=>`<div class="avoidRow">${esc(x)}</div>`).join("")}`:"";
  }
  if(compare){
    const rows=Array.isArray(analysis.squads)?analysis.squads:[];
    compare.innerHTML=rows.map(x=>`<div class="compareRow"><span class="compareNo">${esc(x.id)}</span><div><b>${esc(x.name||`${t("squad")} ${x.id}`)}</b><small>${esc(x.status||"")}${x.optional?"":` · ${t("pro_data_quality")} ${esc(x.data_quality??0)}% · ${esc(x.heroes_detected??0)}/5 ${esc(ui.heroes)}`}${x.composition_complete?" ✓":""}</small></div><strong>${esc(x.power_label||"—")}</strong></div>`).join("");
  }
  const shop=analysis.shop||{};
  if(shopSummary)shopSummary.textContent=shop.summary||t("shop_summary_default");
  if(shopConfidence)shopConfidence.textContent=shop.confidence_label||`${shop.confidence||0}%`;
  if(shopCatalogPill){shopCatalogPill.textContent=shop.catalog_label||"—";shopCatalogPill.className=`pill ${shop.catalog_status==="official"?"catalogOfficialPill":"catalogPartialPill"}`;}
  if(shopList){
    const rows=(Array.isArray(shop.recommendations)?shop.recommendations:[]).slice(0,3);
    shopList.innerHTML=rows.length?rows.map(x=>`<article class="shopCard ${esc(x.verdict_key||"")}"><div class="shopHead"><span class="shopRank">${esc(x.rank||"•")}</span><div><b>${esc(x.item||"")}</b><small>${esc(x.store||"")}${x.price_label?` · ${esc(x.price_label)}`:""}</small>${x.score_label?`<span class="shopScore">${esc(x.score_label)}</span>`:""}</div><span class="shopVerdict">${esc(x.verdict||"")}</span></div><details class="decisionDetails"><summary>${esc(ui.details)}</summary><p>${esc(x.reason||"")}</p>${x.target?`<strong>${esc(x.target)}</strong>`:""}</details></article>`).join(""):`<div class="notice">${esc(t("shop_no_recommendations"))}</div>`;
  }
}

function memberActivity(m){
  const now=Date.now(),ts=Date.parse(m?.last_active_at||m?.updated_at||"");
  const ageH=Number.isFinite(ts)?Math.max(0,(now-ts)/36e5):null;
  let score=0,signals=0;
  if(ageH!==null){signals++;score+=ageH<=24?55:ageH<=72?42:ageH<=168?24:8}
  const delta=Number(m?.delta_m);if(Number.isFinite(delta)){signals++;score+=delta>0?25:delta===0?8:4}
  const vs=Number(m?.vs_points);if(Number.isFinite(vs)){signals++;score+=vs>0?12:2}
  const season=Number(m?.season_points);if(Number.isFinite(season)){signals++;score+=season>0?8:1}
  if(!signals)return {score:null,key:"unknown",ageH:null};
  score=Math.max(0,Math.min(100,Math.round(score)));
  const key=score>=72?"very_active":score>=52?"active":score>=28?"low": "inactive";
  return {score,key,ageH};
}
function renderAllianceActivity(){
  const members=state.alliance.members||[],box=$("#activitySummary"),counts={active:0,watch:0,inactive:0,unknown:0};
  const scored=members.map(m=>({m,a:memberActivity(m)}));
  scored.forEach(({a})=>{if(a.key==="very_active"||a.key==="active")counts.active++;else if(a.key==="low")counts.watch++;else if(a.key==="inactive")counts.inactive++;else counts.unknown++});
  if(box)box.innerHTML=`<div><b>🟢 ${counts.active}</b><small>${esc(t("activity_active"))}</small></div><div><b>🟠 ${counts.watch}</b><small>${esc(t("activity_watch"))}</small></div><div><b>🔴 ${counts.inactive}</b><small>${esc(t("activity_inactive"))}</small></div>`;
  const note=$("#activityNote");if(note)note.textContent=members.length?t("activity_estimated_note"):t("activity_no_data");
  return scored;
}
function renderMembers(){const box=$("#memberList"),members=state.alliance.members||[];if(!box)return;renderAllianceActivity();box.innerHTML=members.length?members.map(m=>{const a=memberActivity(m),icon=a.key==="very_active"||a.key==="active"?"🟢":a.key==="low"?"🟠":a.key==="inactive"?"🔴":"⚪",label=t(`activity_${a.key}`),score=a.score===null?"—":`${a.score}/100`;return `<div class="member"><div><b>${icon} ${esc(m.name||t("player"))}</b><small>${t("hq")} ${m.hq_level??"—"} · ${fmtPower(m.power_m)} · ${m.role||"R1"}</small><span class="activityLine">${esc(label)} · ${esc(score)}</span></div><div class="delta">${m.delta_m?`${m.delta_m>0?"+":""}${m.delta_m} M`:"—"}</div></div>`}).join(""):`<div class="notice">${t("no_members")}</div>`}
function renderVsTimeline(){const active=Number(state.vs.day||1),fmt=new Intl.DateTimeFormat(locale,{weekday:"short"}),monday=new Date(Date.UTC(2026,0,5));$("#vsTimeline").innerHTML=Array.from({length:6},(_,i)=>{const d=new Date(monday);d.setUTCDate(monday.getUTCDate()+i);return `<div class="day ${active===i+1?"active":""}">${fmt.format(d)}<br>${t("day_label")}${i+1}</div>`}).join("")}
function renderAdvice(){const p=state.player;if(!p.name){$("#adviceTitle").textContent=t("configure_profile");$("#adviceText").textContent=t("configure_text");$("#adviceAction").textContent=t("configure");return}const populated=state.squads.filter(x=>Number(x.power)>0);if(!populated.length){$("#adviceTitle").textContent=t("hello",{name:p.name});$("#adviceText").textContent=t("sync_four");$("#adviceAction").textContent=t("open_player");return}const strongest=[...populated].sort((x,y)=>(Number(y.power)||0)-(Number(x.power)||0))[0];$("#adviceTitle").textContent=t("priority",{name:strongest.name||`${t("squad")} 1`});$("#adviceText").textContent=t("priority_text",{power:fmtPower(strongest.power)});$("#adviceAction").textContent=t("view_squads")}
function renderAccountFields(){const p=state.player;if(!$("#fName"))return;$("#fName").value=p.name||"";$("#fServer").value=p.server_id||"";$("#fHq").value=p.hq_level||"";$("#fAlliance").value=state.alliance.tag||"";$("#fRole").value=state.alliance.role||p.role||"R1"}
function renderProvider(){const s=state.sync||{},sources=s.sources||{},official=Boolean(sources.official),pill=$("#providerPill"),box=$("#providerStatus");if(!pill||!box)return;pill.textContent=official?t("official_connected"):t("official_pending");pill.className=`pill ${official?"activePill":""}`;$("#publicSourceState").textContent=official?t("official_connected"):t("official_pending");$("#scanSourceState").textContent=(sources.scan||s.last_scan)?t("available"):t("ready");$("#allianceCloudState").textContent=(sources.alliance||cloudSession)?t("available"):t("not_connected");if(s.last_error&&s.status==="offline"){box.className="notice warn";box.textContent=s.last_error}else if(official){box.className="notice";box.textContent=s.official_last_sync?t("last_update",{ago:fmtAgo(s.official_last_sync)}):t("official_connected_note")}else{box.className="notice warn";box.textContent=t("hybrid_no_public")}}
function ensureInviteCode(){if(!state.alliance.invite_code){const base=(state.alliance.tag||"WB").replace(/[^A-Z0-9]/gi,"").toUpperCase().slice(0,4)||"WB";state.alliance.invite_code=`${base}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;localStorage.setItem(STORE_KEY,JSON.stringify(state))}return state.alliance.invite_code}
function openDrawer(name){closeDrawers();$("#backdrop").classList.add("open");const d=$("#"+name+"Drawer");if(d){d.classList.add("open");d.setAttribute("aria-hidden","false")}}
function closeDrawers(){$("#backdrop").classList.remove("open");$$('.drawer').forEach(d=>{d.classList.remove("open");d.setAttribute("aria-hidden","true")})}

$$('[data-open]').forEach(b=>b.addEventListener("click",()=>openDrawer(b.dataset.open)));$$('[data-close]').forEach(b=>b.addEventListener("click",closeDrawers));$("#backdrop").addEventListener("click",closeDrawers);$("#accountBtn").addEventListener("click",()=>openDrawer("account"));$("#adviceAction").addEventListener("click",()=>openDrawer(state.player.name?"player":"account"));$("#languageSelect").addEventListener("change",e=>{languageChoice=e.target.value;localStorage.setItem(LANG_KEY,languageChoice);applyLanguage()});
$("#saveProfileBtn").addEventListener("click",async()=>{state.player.name=$("#fName").value.trim();state.player.server_id=$("#fServer").value.trim();state.player.hq_level=Number($("#fHq").value)||null;state.player.role=($("#fRole").value.trim().toUpperCase()||"R1");state.alliance.tag=$("#fAlliance").value.trim().toUpperCase();state.alliance.role=state.player.role;state.vs.our_alliance=state.alliance.tag;saveState();await joinPendingAlliance();closeDrawers()});

async function syncAll(){const btns=[$("#syncAllBtn"),$("#syncPlayerBtn")].filter(Boolean);btns.forEach(b=>{b.disabled=true;b.textContent=t("syncing")});try{const r=await fetch("/api/sync",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({state,locale:lang})});const j=await r.json().catch(()=>({}));if(r.ok&&j.state){state=mergeState(state,j.state);state.sync={...state.sync,status:"ok",provider:j.provider||state.sync.provider||"warboost-local",provider_kind:j.provider_kind||state.sync.provider_kind||"local",capabilities:j.capabilities||state.sync.capabilities||[],last_sync:j.synced_at||new Date().toISOString(),last_error:null,sources:{...state.sync.sources,...j.sources}};saveState();$("#playerSyncInfo").textContent=(state.sync.sources?.official?t("official_sync_done"):t("public_done"))}else{state.sync.last_error=j.message||j.error||t("hybrid_no_public");state.sync.status="waiting";saveState()}}catch{state.sync.last_error=t("offline_keep");state.sync.status="offline";saveState()}finally{btns.forEach((b,i)=>{b.disabled=false;b.textContent=i===0?t("public_refresh"):t("public_button")})}}
$("#syncAllBtn").addEventListener("click",syncAll);$("#syncPlayerBtn").addEventListener("click",syncAll);
$("#openScanBtn").addEventListener("click",()=>openDrawer("scan"));$("#scanPlayerBtn").addEventListener("click",()=>openDrawer("scan"));$("#scanShopBtn")?.addEventListener("click",()=>{openDrawer("scan");renderScanTypeOptions();if($("#scanType"))$("#scanType").value="shop"});

async function imageToDataUrl(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{const max=2048,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);let data=c.toDataURL("image/jpeg",.9);if(data.length>3900000)data=c.toDataURL("image/jpeg",.78);URL.revokeObjectURL(url);resolve(data)}catch(e){reject(e)}};img.onerror=e=>{URL.revokeObjectURL(url);reject(e)};img.src=url})}
$("#scanFile").addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;try{scanImageData=await imageToDataUrl(file);$("#scanPreview").src=scanImageData;$("#scanPreview").classList.remove("hidden");$("#scanStatus").className="notice";$("#scanStatus").textContent=t("scan_ready")}catch{$("#scanStatus").className="notice warn";$("#scanStatus").textContent=t("scan_error")}});
$("#analyzeScanBtn").addEventListener("click",async()=>{if(!scanImageData){$("#scanStatus").className="notice warn";$("#scanStatus").textContent=t("scan_wait");return}if(!cloudSession?.access_token){openDrawer("account");authMessage(t("connect_pro"));return}const btn=$("#analyzeScanBtn");btn.disabled=true;btn.textContent=t("scan_processing");$("#scanStatus").className="notice";$("#scanStatus").textContent=t("scan_processing");try{const r=await fetch("/api/scan",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({scan_type:$("#scanType").value,locale:lang,image_data_url:scanImageData,current_state:state})});const j=await r.json().catch(()=>({}));if(r.ok&&j.state){const scanType=$("#scanType").value;const sm=String(scanType||"").match(/^squad([1-4])$/i);let suggestedNames=[];if(sm){const idx=Number(sm[1])-1;const incomingSq=j.state.squads?.[idx];if(incomingSq?.heroes){suggestedNames=incomingSq.heroes.slice(0,5).map(h=>String(h?.name||"").trim());incomingSq.heroes=incomingSq.heroes.map(h=>{const x={...(h||{})};delete x.name;return x})}}state=mergeState(state,j.state);if(sm){const target=state.squads?.[Number(sm[1])-1];if(target?.heroes)for(const h of target.heroes){if(isGenericHeroName(h?.name))h.name=""}}state.sync.last_scan=j.scanned_at||new Date().toISOString();state.sync.sources={...state.sync.sources,scan:true};saveState();$("#proPriorityPanel")?.classList.add("hidden");$("#playerSyncInfo")?.classList.remove("hidden");if(sm){const count=suggestedNames.filter(Boolean).length;$("#scanStatus").className="notice warn";$("#scanStatus").textContent=count>0?t("hero_auto_recognized",{count}):t("hero_confirm_needed");startHeroConfirmation(Number(sm[1]),suggestedNames)}else{$("#scanStatus").className="notice";$("#scanStatus").textContent=t("scan_saved");closeHeroConfirmation(true)}}else{$("#scanStatus").className="notice warn";$("#scanStatus").textContent=j.code==="SCAN_NOT_CONFIGURED"?t("scan_unconfigured"):(j.message||t("scan_error"))}}catch{$("#scanStatus").className="notice warn";$("#scanStatus").textContent=t("scan_error")}finally{btn.disabled=false;btn.textContent=t("analyze")}});

async function requestAdvice(scope){try{const r=await fetch("/api/advice",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({scope,state,locale:lang})});const j=await r.json().catch(()=>({}));if(r.ok)return j}catch{}return null}
async function runPlayerAdvice(scrollShop=false){if(!requirePro())return;const buttons=[$("#playerAdviceBtn"),$("#shopAdviceBtn")].filter(Boolean),note=$("#playerSyncInfo"),panel=$("#proPriorityPanel"),labels=buttons.map(b=>b.textContent);buttons.forEach(b=>{b.disabled=true;b.textContent=t("pro_analyzing")});if(note){note.classList.remove("hidden");note.textContent=t("pro_analyzing")}if(panel)panel.classList.add("hidden");const j=await requestAdvice("player");if(j?.analysis){renderProPriority(j.analysis);if(scrollShop)setTimeout(()=>$("#proShopList")?.scrollIntoView({behavior:"smooth",block:"start"}),120)}else if(note)note.textContent=j?.advice||t("player_sync_note");buttons.forEach((b,i)=>{b.disabled=false;b.textContent=labels[i]})}
$("#playerAdviceBtn").addEventListener("click",()=>runPlayerAdvice(false));$("#shopAdviceBtn")?.addEventListener("click",()=>runPlayerAdvice(true));
$("#warPlanBtn").addEventListener("click",async()=>{if(!requirePro())return;$("#warPlanText").textContent=await getAdvice("alliance")});$("#vsPlanBtn").addEventListener("click",async()=>{if(!requirePro())return;$("#vsPlanText").textContent=await getAdvice("vs")});$("#seasonAdviceBtn").addEventListener("click",async()=>{if(!requirePro())return;$("#seasonAdviceText").textContent=await getAdvice("season")});
async function getAdvice(scope){const j=await requestAdvice(scope);if(j?.advice)return j.advice;return scope==="alliance"?t("war_plan_empty"):scope==="vs"?t("vs_empty"):scope==="season"?t("season_empty"):t("player_sync_note")}

$("#shareInviteBtn").addEventListener("click",async()=>{let code=ensureInviteCode();try{const rr=await fetch("/api/invite",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({tag:state.alliance.tag||"WB",name:state.alliance.name||state.alliance.tag||"WarBoost",invite_code:code,role:state.alliance.role||state.player.role||"R1"})});const jj=await rr.json().catch(()=>({}));if(rr.ok&&jj.invite_code){code=jj.invite_code;state.alliance.id=jj.alliance?.id||state.alliance.id;state.alliance.invite_code=code;state.sync.sources={...state.sync.sources,alliance:true};saveState()}}catch{}const url=`${location.origin}${location.pathname}?join=${encodeURIComponent(code)}`,text=`WarBoost · ${code}`;try{if(navigator.share)await navigator.share({title:`WarBoost · ${t("alliance")}`,text,url});else{await navigator.clipboard.writeText(`${text}\n${url}`);$("#shareInviteBtn").textContent=t("copy");setTimeout(()=>$("#shareInviteBtn").textContent=t("share"),1400)}}catch{}});
async function joinPendingAlliance(){const code=String(state.alliance.invite_code||"").trim();if(!code||!state.player.name||!cloudSession?.access_token)return;try{const r=await fetch("/api/join",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({invite_code:code,role:state.player.role||"R1"})});const j=await r.json().catch(()=>({}));if(r.ok&&j.alliance){state.alliance.id=j.alliance.id||state.alliance.id;state.alliance.tag=j.alliance.tag||state.alliance.tag;state.alliance.name=j.alliance.name||state.alliance.name;state.vs.our_alliance=state.alliance.tag;state.sync.sources={...state.sync.sources,alliance:true};saveState()}}catch{}}
function handleJoinLink(){const code=new URLSearchParams(location.search).get("join");if(!code)return;state.alliance.invite_code=code.toUpperCase();localStorage.setItem(STORE_KEY,JSON.stringify(state));setTimeout(()=>openDrawer("account"),500)}

function formatProPrice(plan){if(!plan?.amount)return "PRO";try{const value=new Intl.NumberFormat(locale,{style:"currency",currency:String(plan.currency||"eur").toUpperCase()}).format(Number(plan.amount)/100),period=plan.interval==="year"?t("per_year"):plan.interval==="month"?t("per_month"):"";return `${value}${period}`}catch{return "PRO"}}
function proMessage(text,ok=false){const el=$("#proMessage");if(!el)return;el.className=`notice${ok?"":" warn"}`;el.textContent=text}
function renderPro(){const pill=$("#proPill"),btn=$("#proActionBtn"),title=$("#proTitle"),price=$("#proPrice");if(!pill||!btn)return;const logged=Boolean(cloudSession?.user);pill.textContent=proState.active?"PRO":t("free");pill.classList.toggle("active",proState.active);title.textContent=proState.active?t("pro_active"):t("upgrade");if(!logged){price.textContent=t("connect_for_pro");btn.textContent=t("login");btn.disabled=false;return}if(!proState.configured){price.textContent=t("pro_config");btn.textContent=t("pro_soon");btn.disabled=true;return}const formatted=formatProPrice(proState.plan);price.textContent=proState.active?t("subscription_active",{price:formatted}):formatted;btn.textContent=proState.active?t("manage_subscription"):t("go_pro");btn.disabled=false}
async function refreshPro(){if(!cloudSession?.access_token){proState={active:false,status:"free",configured:false,plan:null};renderPro();return}try{const r=await fetch("/api/pro",{cache:"no-store",headers:authHeaders()});const j=await r.json().catch(()=>({}));if(r.ok)proState={active:Boolean(j.active),status:j.status||"free",configured:Boolean(j.configured),plan:j.plan||null};else proState={active:false,status:"free",configured:false,plan:null}}catch{proState={active:false,status:"free",configured:false,plan:null}}renderPro()}
function requirePro(){if(proState.active)return true;openDrawer("account");setTimeout(()=>$("#proSection")?.scrollIntoView({behavior:"smooth",block:"center"}),160);proMessage(cloudSession?.user?t("pro_required"):t("connect_pro"));return false}
async function openProAction(){if(!cloudSession?.access_token){proMessage(t("connect_for_pro"));$("#authEmail")?.focus();return}const btn=$("#proActionBtn");if(!proState.configured){proMessage(t("pro_config"));return}btn.disabled=true;const original=btn.textContent;btn.textContent="…";try{const action=proState.active?"portal":"checkout",r=await fetch(`/api/pro?action=${action}`,{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({action})}),j=await r.json().catch(()=>({}));if(!r.ok||!j.url)throw new Error(j.message||"Stripe");location.href=j.url}catch(e){proMessage(e.message||"Stripe");btn.disabled=false;btn.textContent=original}}
$("#proActionBtn")?.addEventListener("click",openProAction);const proReturn=new URLSearchParams(location.search).get("pro");if(proReturn){setTimeout(()=>{openDrawer("account");if(proReturn==="success")setTimeout(refreshPro,900)},500);history.replaceState({},"",location.pathname)}

$("#loginBtn")?.addEventListener("click",async()=>{if(!cloud)return authMessage(t("auth_cloud_missing"));const email=$("#authEmail").value.trim().toLowerCase(),password=$("#authPassword").value,{error}=await cloud.auth.signInWithPassword({email,password});if(error)return authMessage(error.message);authMessage(t("auth_success"),true)});
$("#signupBtn")?.addEventListener("click",async()=>{if(!cloud)return authMessage(t("auth_cloud_missing"));const email=$("#authEmail").value.trim().toLowerCase(),password=$("#authPassword").value;if(!email||password.length<6)return authMessage(t("auth_invalid"));const {error}=await cloud.auth.signUp({email,password});if(error)return authMessage(error.message);localStorage.setItem("warboost_v1_pending_email",email);$("#otpBox").classList.remove("hidden");authMessage(t("signup_sent"),true)});
$("#verifyOtpBtn")?.addEventListener("click",async()=>{if(!cloud)return;const email=localStorage.getItem("warboost_v1_pending_email")||$("#authEmail").value.trim().toLowerCase(),token=$("#authOtp").value.replace(/\D/g,"");if(token.length<6||token.length>8)return authMessage(t("otp_full"));const {error}=await cloud.auth.verifyOtp({email,token,type:"email"});if(error)return authMessage(error.message);localStorage.removeItem("warboost_v1_pending_email");authMessage(t("email_confirmed"),true)});
$("#logoutBtn")?.addEventListener("click",async()=>{if(cloud)await cloud.auth.signOut();cloudSession=null;state.player_id=clientId();renderAuth()});

document.addEventListener("click",e=>{const btn=e.target.closest?.("[data-inline-hero-save]");if(!btn)return;e.preventDefault();e.stopPropagation();const container=btn.closest?.("[data-inline-confirm]");saveInlineHeroNames(btn.dataset.inlineHeroSave,container,btn)});
document.addEventListener("click",e=>{const btn=e.target.closest?.(".heroConfirmAction[data-hero-confirm]");if(!btn)return;e.preventDefault();e.stopPropagation();startHeroConfirmation(btn.dataset.heroConfirm)});
$("#saveHeroNamesBtn")?.addEventListener("click",saveHeroConfirmation);$("#skipHeroNamesBtn")?.addEventListener("click",skipHeroConfirmation);
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("/sw.js").catch(()=>{}));
handleJoinLink();applyLanguage();refreshServerTime();pullServerState();initCloudAuth();render();renderAuth();
