import {LANGUAGES,resolveLanguage,localeFor,dirFor,translator} from "./i18n.js";

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE_KEY="warboost_v1_core_state", CLIENT_KEY="warboost_v1_client_id", LANG_KEY="warboost_v12_language";
function uid(){return crypto.randomUUID?.()||`wb-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function clientId(){let id=localStorage.getItem(CLIENT_KEY);if(!id){id=uid();localStorage.setItem(CLIENT_KEY,id)}return id}
function emptyHero(i){return {name:`Hero ${i}`,level:null,stars:null,power:null,exclusive:null,gear:null}}
function emptySquad(i){return {id:i,name:`Squad ${i}`,power:null,updated_at:null,heroes:[1,2,3,4,5].map(emptyHero)}}
function initialState(){return {version:"1.2.6",player_id:clientId(),updated_at:null,player:{name:"",server_id:"",hq_level:null,power_m:null,coordinates:null,role:"R1"},exclusive_weapons:[],drone:{level:null,power_m:null,updated_at:null},squads:[1,2,3,4].map(emptySquad),alliance:{id:null,tag:"",name:"",role:"R1",invite_code:"",members:[],updated_at:null},vs:{week:null,day:null,our_alliance:"",opponent:"",our_score:null,their_score:null,updated_at:null},season:{name:"",number:null,day:null,total_days:null,profession:"",progress_pct:0,resistance:null,updated_at:null},sync:{provider:"warboost-hybrid",status:"local",last_sync:null,last_error:null,auto_ready:true,last_scan:null,public_last_sync:null,sources:{public:false,scan:false,alliance:false}}}}
function mergeExclusiveWeapons(baseList,incomingList){
  const out=Array.isArray(baseList)?baseList.map(x=>({...x})):[];
  if(!Array.isArray(incomingList))return out;
  const keyOf=x=>String(x?.hero_name||x?.weapon_name||"").trim().toLowerCase();
  for(const item of incomingList){
    if(!item||typeof item!=="object")continue;
    const key=keyOf(item);
    if(!key)continue;
    const idx=out.findIndex(x=>keyOf(x)===key);
    if(idx>=0)out[idx]={...out[idx],...item};
    else out.push({...item});
  }
  return out.slice(0,24);
}
function mergeState(base,incoming){if(!incoming||typeof incoming!=="object")return base;const out={...base,...incoming};out.player={...base.player,...incoming.player};out.drone={...base.drone,...incoming.drone};out.alliance={...base.alliance,...incoming.alliance};out.vs={...base.vs,...incoming.vs};out.season={...base.season,...incoming.season};out.exclusive_weapons=mergeExclusiveWeapons(base.exclusive_weapons,incoming.exclusive_weapons);out.sync={...base.sync,...incoming.sync,sources:{...base.sync.sources,...incoming.sync?.sources}};out.squads=Array.from({length:4},(_,i)=>({...base.squads[i],...(incoming.squads?.[i]||{}),heroes:Array.from({length:5},(_,j)=>({...base.squads[i].heroes[j],...(incoming.squads?.[i]?.heroes?.[j]||{})}))}));out.version="1.2.6";return out}
function loadState(){try{const raw=localStorage.getItem(STORE_KEY);return raw?mergeState(initialState(),JSON.parse(raw)):initialState()}catch{return initialState()}}
let state=loadState(),serverNow=new Date(),pushTimer=null,suppressPush=false,cloud=null,cloudSession=null,proState={active:false,status:"free",configured:false,plan:null},scanImageData=null;
let languageChoice=localStorage.getItem(LANG_KEY)||"auto",lang=resolveLanguage(languageChoice),locale=localeFor(lang),t=translator(lang);
function authHeaders(extra={}){return {...extra,...(cloudSession?.access_token?{authorization:`Bearer ${cloudSession.access_token}`}:{})}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function tpl(key,vars={}){return t(key,vars)}
function fmtPower(v){if(v===null||v===undefined||v==="")return "—";const n=Number(v);if(!Number.isFinite(n))return String(v);return `${new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(n)} M`}
function fmtAgo(iso){if(!iso)return t("never");const d=Math.max(0,Date.now()-new Date(iso).getTime());if(d<60e3)return t("just_now");if(d<3600e3)return `${Math.floor(d/60e3)} ${t("minutes")}`;if(d<86400e3)return `${Math.floor(d/3600e3)} ${t("hours")}`;return `${Math.floor(d/86400e3)} ${t("days")}`}
function isoWeek(d){const x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}
function vsDayFromServer(d){const day=d.getUTCDay();return day===0?6:day}
function renderScanTypeOptions(){const sel=$("#scanType");if(!sel)return;const current=sel.value||"profile";const opts=[["profile",t("scan_profile")],["squad1",`${t("squad")} 1`],["squad2",`${t("squad")} 2`],["squad3",`${t("squad")} 3`],["squad4",`${t("squad")} 4`],["exclusive",t("scan_exclusive")],["drone",t("scan_drone")],["vs",t("scan_vs")],["season",t("scan_season")]];sel.innerHTML=opts.map(([v,label])=>`<option value="${v}">${label}</option>`).join("");sel.value=opts.some(([v])=>v===current)?current:"profile"}
function applyLanguage(){lang=resolveLanguage(languageChoice);locale=localeFor(lang);t=translator(lang);document.documentElement.lang=lang;document.documentElement.dir=dirFor(lang);$$('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});$$('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAria)));const sel=$("#languageSelect");if(sel){sel.innerHTML=LANGUAGES.map(([v,label])=>`<option value="${v}">${label}</option>`).join("");sel.value=languageChoice}renderScanTypeOptions();renderClock();render();renderAuth();renderPro();$("#proPriorityPanel")?.classList.add("hidden");$("#playerSyncInfo")?.classList.remove("hidden")}
function saveState(){state.updated_at=new Date().toISOString();state.version="1.2.6";localStorage.setItem(STORE_KEY,JSON.stringify(state));render();if(!suppressPush)scheduleServerSave()}
function scheduleServerSave(){clearTimeout(pushTimer);pushTimer=setTimeout(pushServerState,700)}

async function initCloudAuth(){try{const r=await fetch("/api/cloud-config",{cache:"no-store"});const cfg=await r.json();if(!r.ok||!cfg.configured||!window.supabase?.createClient)throw new Error();cloud=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await cloud.auth.getSession();await applySession(data?.session||null);cloud.auth.onAuthStateChange((_event,session)=>applySession(session||null))}catch{renderAuth()}}
async function applySession(session){cloudSession=session||null;if(cloudSession?.user?.id){const oldId=state.player_id;state.player_id=cloudSession.user.id;if(oldId!==state.player_id)localStorage.setItem(STORE_KEY,JSON.stringify(state));await pullServerState();await refreshPro()}else{proState={active:false,status:"free",configured:false,plan:null}}renderAuth();renderPro()}
function renderAuth(){const logged=Boolean(cloudSession?.user);$("#authLoggedOut")?.classList.toggle("hidden",logged);$("#authLoggedIn")?.classList.toggle("hidden",!logged);if($("#authPill"))$("#authPill").textContent=logged?t("connected"):(cloud?t("ready"):t("local"));if(logged&&$("#authIdentity"))$("#authIdentity").textContent=`WarBoost · ${cloudSession.user.email||""}`;renderPro()}
function authMessage(text,ok=false){const el=$("#authMessage");if(!el)return;el.className=`notice${ok?"":" warn"}`;el.textContent=text}
async function pushServerState(){if(!cloudSession?.access_token)return;try{const r=await fetch("/api/state",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({state})});if(!r.ok)return;const j=await r.json().catch(()=>({}));if(j?.updated_at){state.sync.last_sync=state.sync.last_sync||j.updated_at;localStorage.setItem(STORE_KEY,JSON.stringify(state))}}catch{}}
async function pullServerState(){if(!cloudSession?.access_token)return;try{const r=await fetch("/api/state",{cache:"no-store",headers:authHeaders()});if(!r.ok)return;const j=await r.json();if(j?.state){suppressPush=true;state=mergeState(state,j.state);localStorage.setItem(STORE_KEY,JSON.stringify(state));render();suppressPush=false}}catch{}}

async function refreshServerTime(){try{const r=await fetch("/api/time",{cache:"no-store"});if(!r.ok)throw new Error();const j=await r.json();serverNow=new Date(j.now);state.vs.week=state.vs.week||j.iso_week;state.vs.day=j.vs_day;$("#syncPill").className="syncState good";$("#syncPill").textContent=t("server_ok")}catch{serverNow=new Date();state.vs.week=state.vs.week||isoWeek(serverNow);state.vs.day=vsDayFromServer(serverNow);$("#syncPill").className="syncState";$("#syncPill").textContent=t("local_time")}renderClock();render()}
function renderClock(){const d=serverNow;const clock=$("#serverClock"),day=$("#serverDay");if(clock)clock.textContent=d.toLocaleTimeString(locale,{hour:"2-digit",minute:"2-digit",second:"2-digit"});if(day)day.textContent=`${d.toLocaleDateString(locale,{weekday:"long",day:"2-digit",month:"short"})} · ${t("week")} ${isoWeek(d)}`}
setInterval(()=>{serverNow=new Date(serverNow.getTime()+1000);renderClock()},1000);setInterval(refreshServerTime,5*60*1000);

function render(){const p=state.player,a=state.alliance,v=state.vs,s=state.season,d=state.drone||{};if(!$("#playerMeta"))return;$("#playerMeta").textContent=p.name?(p.hq_level?`${t("hq")} ${p.hq_level}`:t("connected")):t("to_connect");$("#allianceMeta").textContent=a.tag||"—";$("#vsMeta").textContent=`${t("week")} ${v.week||isoWeek(serverNow)}`;$("#seasonMeta").textContent=s.name||(s.number?`S${s.number}`:t("to_fill"));$("#pName").textContent=p.name||"—";$("#pHq").textContent=p.hq_level?`${t("hq")} ${p.hq_level}`:"—";$("#pPower").textContent=fmtPower(p.power_m);$("#pDrone").textContent=d.level?`${t("level")}${d.level}${d.power_m?` · ${fmtPower(d.power_m)}`:""}`:"—";renderSquads();renderExclusiveWeapons();$("#aTag").textContent=a.tag||"—";$("#aCount").textContent=String(a.members?.length||0);$("#aRole").textContent=a.role||p.role||"R1";$("#inviteCode").textContent=ensureInviteCode();$("#rosterFresh").textContent=a.updated_at?`${t("update")} ${fmtAgo(a.updated_at)}`:t("sync_needed");renderMembers();$("#vsWeekTitle").textContent=t("vs_week",{week:v.week||isoWeek(serverNow)});$("#vsDayPill").textContent=t("day_n",{day:v.day||vsDayFromServer(serverNow)});$("#vsUs").textContent=v.our_alliance||a.tag||t("your_alliance");$("#vsThem").textContent=v.opponent||t("unknown_opponent");$("#vsUsScore").textContent=v.our_score??"—";$("#vsThemScore").textContent=v.their_score??"—";renderVsTimeline();$("#sName").textContent=s.name||(s.number?`S${s.number}`:"—");$("#sDay").textContent=s.day||"—";$("#sProfession").textContent=s.profession||"—";const pct=Math.max(0,Math.min(100,Number(s.progress_pct||0)));$("#seasonProgressBar").style.width=`${pct}%`;$("#seasonProgressLabel").textContent=`${pct}%`;$("#seasonStatus").textContent=s.updated_at?`${t("last_update",{ago:fmtAgo(s.updated_at)})} · ${s.resistance??"—"}`:t("season_wait");renderAdvice();renderAccountFields();renderProvider()}
function squadHasSavedData(sq){return Boolean(sq?.updated_at||Number(sq?.power)>0||(sq?.heroes||[]).some(h=>h?.name||h?.level||h?.stars||h?.power||h?.exclusive||h?.gear))}
function renderSquads(){const box=$("#squadList");if(!box)return;box.innerHTML="";state.squads.forEach((sq,i)=>{const el=document.createElement("div");el.className="squad";const name=sq.name&& !/^Squad \d$/i.test(sq.name)&&!/^Escouade \d$/i.test(sq.name)?sq.name:`${t("squad")} ${i+1}`;const optional4=i===3&&!squadHasSavedData(sq);const freshness=optional4?t("optional_squad4"):(sq.updated_at?`${t("update")} ${fmtAgo(sq.updated_at)}`:t("not_synced"));el.innerHTML=`<button class="squadHead"><span class="squadNo">${i+1}</span><span class="squadName"><b>${esc(name)}</b><small>${esc(freshness)}</small></span><span class="squadPower">${fmtPower(sq.power)}</span><span class="chev">⌄</span></button><div class="squadBody">${(sq.heroes||[]).map((h,j)=>{const hn=h.name&&!/^Hero \d$/i.test(h.name)&&!/^Héros \d$/i.test(h.name)?h.name:`${t("hero")} ${j+1}`;return `<div class="heroRow"><div class="heroAvatar">${j+1}</div><div class="heroInfo"><b>${esc(hn)}</b><small>${h.level?`${t("level")}${h.level}`:`${t("level")}—`} · ${h.stars?`${h.stars}★`:"★—"}${(()=>{const w=weaponForHero(hn);const ex=w?.level??h.exclusive;return ex?` · ${esc(t("exclusive_short"))} ${esc(ex)}`:""})()}${h.gear?` · ${esc(h.gear)}`:""}</small></div><div class="heroPwr">${fmtPower(h.power)}</div></div>`}).join("")}</div>`;el.querySelector(".squadHead").addEventListener("click",()=>el.classList.toggle("open"));box.appendChild(el)})}

function fmtWeaponPower(v){
  const n=Number(v);if(!Number.isFinite(n))return "—";
  if(n>=1_000_000)return new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(n/1_000_000)+" M";
  return new Intl.NumberFormat(locale,{maximumFractionDigits:0}).format(n);
}
function normalizedName(v){return String(v||"").trim().toLowerCase().replace(/\s+/g," ")}
function weaponForHero(name){
  const n=normalizedName(name);if(!n)return null;
  return (state.exclusive_weapons||[]).find(w=>normalizedName(w.hero_name)===n)||null;
}
function renderExclusiveWeapons(){
  const box=$("#exclusiveWeaponList"),count=$("#exclusiveWeaponCount");if(!box)return;
  const list=(state.exclusive_weapons||[]).filter(w=>w&&(w.hero_name||w.weapon_name||w.level||w.power));
  if(count)count.textContent=String(list.length);
  if(!list.length){
    box.innerHTML=`<div class="exclusiveEmpty">${esc(t("exclusive_empty"))}</div>`;
    return;
  }
  box.innerHTML=list.map(w=>{
    const title=w.weapon_name||t("exclusive_weapon");
    const hero=w.hero_name||t("hero");
    const level=w.level?`${t("level")}${esc(w.level)}`:t("level")+"—";
    const power=w.power?fmtWeaponPower(w.power):"—";
    const stats=[
      w.hero_hp_bonus!=null?`${t("exclusive_hp")} +${new Intl.NumberFormat(locale).format(Number(w.hero_hp_bonus))}`:null,
      w.hero_atk_bonus!=null?`${t("exclusive_atk")} +${new Intl.NumberFormat(locale).format(Number(w.hero_atk_bonus))}`:null,
      w.hero_def_bonus!=null?`${t("exclusive_def")} +${new Intl.NumberFormat(locale).format(Number(w.hero_def_bonus))}`:null,
      w.all_damage_resistance_pct!=null?`${t("exclusive_resistance")} ${new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(Number(w.all_damage_resistance_pct))}%`:null,
      w.max_skill_level!=null?`${t("exclusive_skill_cap")} ${new Intl.NumberFormat(locale,{maximumFractionDigits:0}).format(Number(w.max_skill_level))}`:null
    ].filter(Boolean);
    return `<div class="exclusiveCard"><div class="exclusiveIcon">⚔️</div><div class="exclusiveMain"><b>${esc(hero)} · ${esc(title)}</b><small>${esc(level)} · ${esc(t("exclusive_power"))} ${esc(power)}</small>${stats.length?`<span>${esc(stats.join(" · "))}</span>`:""}</div></div>`;
  }).join("");
}

function renderProPriority(analysis){
  const panel=$("#proPriorityPanel"),summary=$("#proPrioritySummary"),list=$("#proPriorityList"),compare=$("#proSquadCompare"),confidence=$("#proConfidence"),note=$("#playerSyncInfo");
  if(!panel||!analysis)return;
  if(note)note.classList.add("hidden");
  panel.classList.remove("hidden");
  if(summary)summary.textContent=analysis.summary||"";
  if(confidence)confidence.textContent=analysis.confidence_label||`${analysis.confidence||0}%`;
  if(list){
    const items=Array.isArray(analysis.priorities)?analysis.priorities:[];
    list.innerHTML=items.length?items.map(x=>`<article class="priorityCard"><span class="priorityRank">${esc(x.rank||"•")}</span><div class="priorityMain"><b>${esc(x.title||"")}</b><p>${esc(x.reason||"")}</p><strong>${esc(x.action||"")}</strong><small>🆓 ${esc(x.buy_free||"")}</small><small>💎 ${esc(x.buy_paid||"")}</small></div></article>`).join(""):`<div class="notice">${esc(analysis.summary||t("player_sync_note"))}</div>`;
  }
  if(compare){
    const rows=Array.isArray(analysis.squads)?analysis.squads:[];
    compare.innerHTML=rows.map(x=>`<div class="compareRow"><span class="compareNo">${esc(x.id)}</span><div><b>${esc(x.name||`${t("squad")} ${x.id}`)}</b><small>${esc(x.status||"")}${x.optional?"":` · ${t("pro_data_quality")} ${esc(x.data_quality??0)}%`}</small></div><strong>${esc(x.power_label||"—")}</strong></div>`).join("");
  }
}

function renderMembers(){const box=$("#memberList"),members=state.alliance.members||[];if(!box)return;box.innerHTML=members.length?members.map(m=>`<div class="member"><div><b>${esc(m.name||t("player"))}</b><small>${t("hq")} ${m.hq_level??"—"} · ${fmtPower(m.power_m)} · ${m.role||"R1"}</small></div><div class="delta">${m.delta_m?`${m.delta_m>0?"+":""}${m.delta_m} M`:"—"}</div></div>`).join(""):`<div class="notice">${t("no_members")}</div>`}
function renderVsTimeline(){const active=Number(state.vs.day||1),fmt=new Intl.DateTimeFormat(locale,{weekday:"short"}),monday=new Date(Date.UTC(2026,0,5));$("#vsTimeline").innerHTML=Array.from({length:6},(_,i)=>{const d=new Date(monday);d.setUTCDate(monday.getUTCDate()+i);return `<div class="day ${active===i+1?"active":""}">${fmt.format(d)}<br>${t("day_label")}${i+1}</div>`}).join("")}
function renderAdvice(){const p=state.player;if(!p.name){$("#adviceTitle").textContent=t("configure_profile");$("#adviceText").textContent=t("configure_text");$("#adviceAction").textContent=t("configure");return}const populated=state.squads.filter(x=>Number(x.power)>0);if(!populated.length){$("#adviceTitle").textContent=t("hello",{name:p.name});$("#adviceText").textContent=t("sync_four");$("#adviceAction").textContent=t("open_player");return}const strongest=[...populated].sort((x,y)=>(Number(y.power)||0)-(Number(x.power)||0))[0];$("#adviceTitle").textContent=t("priority",{name:strongest.name||`${t("squad")} 1`});$("#adviceText").textContent=t("priority_text",{power:fmtPower(strongest.power)});$("#adviceAction").textContent=t("view_squads")}
function renderAccountFields(){const p=state.player;if(!$("#fName"))return;$("#fName").value=p.name||"";$("#fServer").value=p.server_id||"";$("#fHq").value=p.hq_level||"";$("#fAlliance").value=state.alliance.tag||"";$("#fRole").value=state.alliance.role||p.role||"R1"}
function renderProvider(){const s=state.sync||{},sources=s.sources||{};const pill=$("#providerPill"),box=$("#providerStatus");if(!pill||!box)return;pill.textContent=t("hybrid_active");pill.className="pill activePill";$("#publicSourceState").textContent=sources.public?t("available"):t("not_connected");$("#scanSourceState").textContent=(sources.scan||s.last_scan)?t("available"):t("ready");$("#allianceCloudState").textContent=(sources.alliance||cloudSession)?t("available"):t("not_connected");if(s.last_error&&s.status==="offline"){box.className="notice warn";box.textContent=s.last_error}else{box.className="notice";box.textContent=sources.public?(s.last_sync?t("last_update",{ago:fmtAgo(s.last_sync)}):t("hybrid_active")):t("hybrid_no_public")}}
function ensureInviteCode(){if(!state.alliance.invite_code){const base=(state.alliance.tag||"WB").replace(/[^A-Z0-9]/gi,"").toUpperCase().slice(0,4)||"WB";state.alliance.invite_code=`${base}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;localStorage.setItem(STORE_KEY,JSON.stringify(state))}return state.alliance.invite_code}
function openDrawer(name){closeDrawers();$("#backdrop").classList.add("open");const d=$("#"+name+"Drawer");if(d){d.classList.add("open");d.setAttribute("aria-hidden","false")}}
function closeDrawers(){$("#backdrop").classList.remove("open");$$('.drawer').forEach(d=>{d.classList.remove("open");d.setAttribute("aria-hidden","true")})}

$$('[data-open]').forEach(b=>b.addEventListener("click",()=>openDrawer(b.dataset.open)));$$('[data-close]').forEach(b=>b.addEventListener("click",closeDrawers));$("#backdrop").addEventListener("click",closeDrawers);$("#accountBtn").addEventListener("click",()=>openDrawer("account"));$("#adviceAction").addEventListener("click",()=>openDrawer(state.player.name?"player":"account"));$("#languageSelect").addEventListener("change",e=>{languageChoice=e.target.value;localStorage.setItem(LANG_KEY,languageChoice);applyLanguage()});
$("#saveProfileBtn").addEventListener("click",async()=>{state.player.name=$("#fName").value.trim();state.player.server_id=$("#fServer").value.trim();state.player.hq_level=Number($("#fHq").value)||null;state.player.role=($("#fRole").value.trim().toUpperCase()||"R1");state.alliance.tag=$("#fAlliance").value.trim().toUpperCase();state.alliance.role=state.player.role;state.vs.our_alliance=state.alliance.tag;saveState();await joinPendingAlliance();closeDrawers()});

async function syncAll(){const btns=[$("#syncAllBtn"),$("#syncPlayerBtn")].filter(Boolean);btns.forEach(b=>{b.disabled=true;b.textContent=t("syncing")});try{const r=await fetch("/api/sync",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({state,locale:lang})});const j=await r.json().catch(()=>({}));if(r.ok&&j.state){state=mergeState(state,j.state);state.sync={...state.sync,status:"ok",provider:j.provider||"warboost-hybrid",last_sync:j.synced_at||new Date().toISOString(),last_error:null,sources:{...state.sync.sources,...j.sources}};saveState();$("#playerSyncInfo").textContent=t("public_done")}else{state.sync.last_error=j.message||j.error||t("hybrid_no_public");state.sync.status="waiting";saveState()}}catch{state.sync.last_error=t("offline_keep");state.sync.status="offline";saveState()}finally{btns.forEach((b,i)=>{b.disabled=false;b.textContent=i===0?t("public_refresh"):t("public_button")})}}
$("#syncAllBtn").addEventListener("click",syncAll);$("#syncPlayerBtn").addEventListener("click",syncAll);
$("#openScanBtn").addEventListener("click",()=>openDrawer("scan"));$("#scanPlayerBtn").addEventListener("click",()=>openDrawer("scan"));$("#scanExclusiveBtn")?.addEventListener("click",()=>{openDrawer("scan");renderScanTypeOptions();if($("#scanType"))$("#scanType").value="exclusive"});

async function imageToDataUrl(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);const data=c.toDataURL("image/jpeg",.82);URL.revokeObjectURL(url);resolve(data)}catch(e){reject(e)}};img.onerror=e=>{URL.revokeObjectURL(url);reject(e)};img.src=url})}
$("#scanFile").addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;try{scanImageData=await imageToDataUrl(file);$("#scanPreview").src=scanImageData;$("#scanPreview").classList.remove("hidden");$("#scanStatus").className="notice";$("#scanStatus").textContent=t("scan_ready")}catch{$("#scanStatus").className="notice warn";$("#scanStatus").textContent=t("scan_error")}});
$("#analyzeScanBtn").addEventListener("click",async()=>{if(!scanImageData){$("#scanStatus").className="notice warn";$("#scanStatus").textContent=t("scan_wait");return}if(!cloudSession?.access_token){openDrawer("account");authMessage(t("connect_pro"));return}const btn=$("#analyzeScanBtn");btn.disabled=true;btn.textContent=t("scan_processing");$("#scanStatus").className="notice";$("#scanStatus").textContent=t("scan_processing");try{const r=await fetch("/api/scan",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({scan_type:$("#scanType").value,locale:lang,image_data_url:scanImageData,current_state:state})});const j=await r.json().catch(()=>({}));if(r.ok&&j.state){state=mergeState(state,j.state);state.sync.last_scan=j.scanned_at||new Date().toISOString();state.sync.sources={...state.sync.sources,scan:true};saveState();$("#proPriorityPanel")?.classList.add("hidden");$("#playerSyncInfo")?.classList.remove("hidden");$("#scanStatus").className="notice";$("#scanStatus").textContent=t("scan_saved");scanImageData=null;$("#scanFile").value="";$("#scanPreview").classList.add("hidden")}else{$("#scanStatus").className="notice warn";$("#scanStatus").textContent=j.code==="SCAN_NOT_CONFIGURED"?t("scan_unconfigured"):(j.message||t("scan_error"))}}catch{$("#scanStatus").className="notice warn";$("#scanStatus").textContent=t("scan_error")}finally{btn.disabled=false;btn.textContent=t("analyze")}});

async function requestAdvice(scope){try{const r=await fetch("/api/advice",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({scope,state,locale:lang})});const j=await r.json().catch(()=>({}));if(r.ok)return j}catch{}return null}
$("#playerAdviceBtn").addEventListener("click",async()=>{if(!requirePro())return;const btn=$("#playerAdviceBtn"),note=$("#playerSyncInfo"),panel=$("#proPriorityPanel");btn.disabled=true;const old=btn.textContent;btn.textContent=t("pro_analyzing");if(note){note.classList.remove("hidden");note.textContent=t("pro_analyzing")}if(panel)panel.classList.add("hidden");const j=await requestAdvice("player");if(j?.analysis)renderProPriority(j.analysis);else if(note)note.textContent=j?.advice||t("player_sync_note");btn.disabled=false;btn.textContent=old});
$("#warPlanBtn").addEventListener("click",async()=>{if(!requirePro())return;$("#warPlanText").textContent=await getAdvice("alliance")});$("#vsPlanBtn").addEventListener("click",async()=>{if(!requirePro())return;$("#vsPlanText").textContent=await getAdvice("vs")});$("#seasonAdviceBtn").addEventListener("click",async()=>{if(!requirePro())return;$("#seasonAdviceText").textContent=await getAdvice("season")});
async function getAdvice(scope){const j=await requestAdvice(scope);if(j?.advice)return j.advice;return scope==="alliance"?t("war_plan_empty"):scope==="vs"?t("vs_empty"):scope==="season"?t("season_empty"):t("player_sync_note")}

$("#shareInviteBtn").addEventListener("click",async()=>{let code=ensureInviteCode();try{const rr=await fetch("/api/invite",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({tag:state.alliance.tag||"WB",name:state.alliance.name||state.alliance.tag||"WarBoost",invite_code:code,role:state.alliance.role||state.player.role||"R1"})});const jj=await rr.json().catch(()=>({}));if(rr.ok&&jj.invite_code){code=jj.invite_code;state.alliance.id=jj.alliance?.id||state.alliance.id;state.alliance.invite_code=code;state.sync.sources={...state.sync.sources,alliance:true};saveState()}}catch{}const url=`${location.origin}${location.pathname}?join=${encodeURIComponent(code)}`,text=`WarBoost · ${code}`;try{if(navigator.share)await navigator.share({title:`WarBoost · ${t("alliance")}`,text,url});else{await navigator.clipboard.writeText(`${text}\n${url}`);$("#shareInviteBtn").textContent=t("copy");setTimeout(()=>$("#shareInviteBtn").textContent=t("share"),1400)}}catch{}});
async function joinPendingAlliance(){const code=String(state.alliance.invite_code||"").trim();if(!code||!state.player.name||!cloudSession?.access_token)return;try{const r=await fetch("/api/join",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({invite_code:code,role:state.player.role||"R1"})});const j=await r.json().catch(()=>({}));if(r.ok&&j.alliance){state.alliance.id=j.alliance.id||state.alliance.id;state.alliance.tag=j.alliance.tag||state.alliance.tag;state.alliance.name=j.alliance.name||state.alliance.name;state.vs.our_alliance=state.alliance.tag;state.sync.sources={...state.sync.sources,alliance:true};saveState()}}catch{}}
function handleJoinLink(){const code=new URLSearchParams(location.search).get("join");if(!code)return;state.alliance.invite_code=code.toUpperCase();localStorage.setItem(STORE_KEY,JSON.stringify(state));setTimeout(()=>openDrawer("account"),500)}

function formatProPrice(plan){if(!plan?.amount)return "PRO";try{const value=new Intl.NumberFormat(locale,{style:"currency",currency:String(plan.currency||"eur").toUpperCase()}).format(Number(plan.amount)/100),period=plan.interval==="year"?t("per_year"):plan.interval==="month"?t("per_month"):"";return `${value}${period}`}catch{return "PRO"}}
function proMessage(text,ok=false){const el=$("#proMessage");if(!el)return;el.className=`notice${ok?"":" warn"}`;el.textContent=text}
function renderPro(){const pill=$("#proPill"),btn=$("#proActionBtn"),title=$("#proTitle"),price=$("#proPrice");if(!pill||!btn)return;const logged=Boolean(cloudSession?.user);pill.textContent=proState.active?"PRO":t("free");pill.classList.toggle("active",proState.active);title.textContent=proState.active?t("pro_active"):t("upgrade");if(!logged){price.textContent=t("connect_for_pro");btn.textContent=t("login");btn.disabled=false;return}if(!proState.configured){price.textContent=t("pro_config");btn.textContent=t("pro_soon");btn.disabled=true;return}const formatted=formatProPrice(proState.plan);price.textContent=proState.active?t("subscription_active",{price:formatted}):formatted;btn.textContent=proState.active?t("manage_subscription"):t("go_pro");btn.disabled=false}
async function refreshPro(){if(!cloudSession?.access_token){proState={active:false,status:"free",configured:false,plan:null};renderPro();return}try{const r=await fetch("/api/pro",{cache:"no-store",headers:authHeaders()});const j=await r.json().catch(()=>({}));if(r.ok)proState={active:Boolean(j.active),status:j.status||"free",configured:Boolean(j.configured),plan:j.plan||null};else proState={active:false,status:"free",configured:false,plan:null}}catch{proState={active:false,status:"free",configured:false,plan:null}}renderPro()}
function requirePro(){if(proState.active)return true;openDrawer("account");setTimeout(()=>$("#proSection")?.scrollIntoView({behavior:"smooth",block:"center"}),160);proMessage(cloudSession?.user?t("pro_required"):t("connect_pro"));return false}
async function openProAction(){if(!cloudSession?.access_token){proMessage(t("connect_for_pro"));$("#authEmail")?.focus();return}const btn=$("#proActionBtn");if(!proState.configured){proMessage(t("pro_config"));return}btn.disabled=true;const original=btn.textContent;btn.textContent="…";try{const action=proState.active?"portal":"checkout",r=await fetch(`/api/pro?action=${action}`,{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify({action})}),j=await r.json().catch(()=>({}));if(!r.ok||!j.url)throw new Error(j.message||"Stripe");location.href=j.url}catch(e){proMessage(e.message||"Stripe");btn.disabled=false;btn.textContent=original}}
$("#proActionBtn")?.addEventListener("click",openProAction);const proReturn=new URLSearchParams(location.search).get("pro");if(proReturn){setTimeout(()=>{openDrawer("account");if(proReturn==="success")setTimeout(refreshPro,900)},500);history.replaceState({},"",location.pathname)}

$("#loginBtn")?.addEventListener("click",async()=>{if(!cloud)return authMessage(t("auth_cloud_missing"));const email=$("#authEmail").value.trim().toLowerCase(),password=$("#authPassword").value,{error}=await cloud.auth.signInWithPassword({email,password});if(error)return authMessage(error.message);authMessage(t("auth_success"),true)});
$("#signupBtn")?.addEventListener("click",async()=>{if(!cloud)return authMessage(t("auth_cloud_missing"));const email=$("#authEmail").value.trim().toLowerCase(),password=$("#authPassword").value;if(!email||password.length<6)return authMessage(t("auth_invalid"));const {error}=await cloud.auth.signUp({email,password});if(error)return authMessage(error.message);localStorage.setItem("warboost_v1_pending_email",email);$("#otpBox").classList.remove("hidden");authMessage(t("signup_sent"),true)});
$("#verifyOtpBtn")?.addEventListener("click",async()=>{if(!cloud)return;const email=localStorage.getItem("warboost_v1_pending_email")||$("#authEmail").value.trim().toLowerCase(),token=$("#authOtp").value.replace(/\D/g,"");if(token.length<6||token.length>8)return authMessage(t("otp_full"));const {error}=await cloud.auth.verifyOtp({email,token,type:"email"});if(error)return authMessage(error.message);localStorage.removeItem("warboost_v1_pending_email");authMessage(t("email_confirmed"),true)});
$("#logoutBtn")?.addEventListener("click",async()=>{if(cloud)await cloud.auth.signOut();cloudSession=null;state.player_id=clientId();renderAuth()});

if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("/sw.js").catch(()=>{}));
handleJoinLink();applyLanguage();refreshServerTime();pullServerState();initCloudAuth();render();renderAuth();
