import {createWarBoostSupabaseAuthClient} from "./lib/browser-auth.js";
const $=s=>document.querySelector(s);let cloud=null,session=null,tickets=[];
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function status(text,warn=false){const el=$("#adminStatus");el.className=`notice${warn?" warn":""}`;el.textContent=text}
function authHeaders(extra={}){return {...extra,...(session?.access_token?{authorization:`Bearer ${session.access_token}`}:{})}}
function fmt(iso){try{return new Intl.DateTimeFormat("fr-FR",{dateStyle:"short",timeStyle:"short"}).format(new Date(iso))}catch{return iso||""}}
function render(){const box=$("#adminTickets");if(!tickets.length){box.innerHTML='<div class="privacyText">Aucun ticket.</div>';return}box.innerHTML=tickets.map(t=>{const msgs=(t.messages||[]).map(m=>`<div class="supportMessage ${m.author_kind==="support"?"support":""}"><b>${m.author_kind==="support"?"Support":"Joueur"} · ${esc(fmt(m.created_at))}</b>${esc(m.body)}</div>`).join("");const attachment=t.attachment_path?`<button class="smallBtn supportAttachmentBtn" data-admin-attachment="${esc(t.id)}">📎 ${esc(t.attachment_name||"Capture")}</button>`:"";return `<article class="supportAdminTicket"><div class="supportTicketHead"><div><div class="supportTicketNo">${esc(t.ticket_no)}</div><div class="supportTicketSubject">${esc(t.subject)}</div><div class="supportTicketMeta">${esc(t.category)} · ${esc(t.nickname||"—")} · ${esc(t.email||"—")} · ${esc(fmt(t.created_at))}</div></div><span class="supportStatus ${esc(t.status)}">${esc(t.status)}</span></div><div class="notice" style="margin-top:8px">${esc(t.description)}</div>${attachment}<div class="supportMessages">${msgs}</div><div class="supportAdminControls"><select data-admin-status="${esc(t.id)}"><option value="received"${t.status==="received"?" selected":""}>Reçu</option><option value="in_progress"${t.status==="in_progress"?" selected":""}>En cours</option><option value="waiting_player"${t.status==="waiting_player"?" selected":""}>Attente joueur</option><option value="resolved"${t.status==="resolved"?" selected":""}>Résolu</option></select><button class="smallBtn" data-admin-save-status="${esc(t.id)}">Enregistrer</button></div><div class="supportReplyRow"><input data-admin-reply-input="${esc(t.id)}" maxlength="5000" placeholder="Réponse au joueur…"/><button class="smallBtn" data-admin-reply="${esc(t.id)}">Répondre</button></div></article>`}).join("");
  box.querySelectorAll("[data-admin-save-status]").forEach(b=>b.addEventListener("click",()=>saveTicketStatus(b.dataset.adminSaveStatus)));
  box.querySelectorAll("[data-admin-reply]").forEach(b=>b.addEventListener("click",()=>reply(b.dataset.adminReply)));
  box.querySelectorAll("[data-admin-attachment]").forEach(b=>b.addEventListener("click",()=>attachment(b.dataset.adminAttachment)));
}
async function load(){if(!session?.access_token)return status("Connecte-toi d’abord à WarBoost sur ce même domaine, puis recharge cette page.",true);status("Chargement des tickets…");try{const r=await fetch("/api/support?admin=1",{cache:"no-store",headers:authHeaders()}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error==="SUPPORT_ADMIN_REQUIRED"?"Ce compte n’est pas autorisé comme administrateur support. Configure WARBOOST_SUPPORT_ADMINS dans Vercel.":(j.message||j.error||"Erreur support"));tickets=Array.isArray(j.tickets)?j.tickets:[];status(`${tickets.length} ticket(s) chargé(s).`);render()}catch(e){status(e.message||"Erreur support",true)}}
async function post(body){const r=await fetch("/api/support",{method:"POST",headers:authHeaders({"content-type":"application/json"}),body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||j.error||"Erreur support");return j}
async function saveTicketStatus(id){const sel=[...document.querySelectorAll("[data-admin-status]")].find(x=>x.dataset.adminStatus===String(id));try{await post({action:"status",ticket_id:id,status:sel?.value||"received"});await load()}catch(e){status(e.message,true)}}
async function reply(id){const input=[...document.querySelectorAll("[data-admin-reply-input]")].find(x=>x.dataset.adminReplyInput===String(id)),body=String(input?.value||"").trim();if(body.length<2)return;try{await post({action:"reply",ticket_id:id,body,as_support:true});if(input)input.value="";await load()}catch(e){status(e.message,true)}}
async function attachment(id){try{const j=await post({action:"attachment",ticket_id:id});if(j.url)window.open(j.url,"_blank","noopener,noreferrer")}catch(e){status(e.message,true)}}
async function init(){try{const r=await fetch("/api/cloud-config",{cache:"no-store"}),cfg=await r.json();if(!r.ok||!cfg?.configured)throw new Error("Cloud WarBoost non configuré.");cloud=createWarBoostSupabaseAuthClient({url:cfg.url,key:cfg.key});const got=await cloud.auth.getSession();session=got.data?.session||null;cloud.auth.onAuthStateChange((_e,s)=>{session=s||null;load()});await load()}catch(e){status(e.message||"Impossible d’ouvrir la console support.",true)}}
$("#adminRefresh")?.addEventListener("click",load);init();
