const OBJECTIVES=new Set(["auto","balanced","pvp","pve","vs","season"]);
const SERVER_PROFILES=new Set(["auto","new","mature","competitive","mixed"]);
function n(v){if(v===null||v===undefined||v==="")return null;const x=Number(v);return Number.isFinite(x)?x:null}
function clamp(v,min=0,max=100){return Math.max(min,Math.min(max,Math.round(Number(v)||0)))}
function txt(v){return String(v||"").trim().toLowerCase()}
export function normalizeObjective(v){const x=txt(v);return OBJECTIVES.has(x)?x:"auto"}
export function normalizeServerProfile(v){const x=txt(v);return SERVER_PROFILES.has(x)?x:"auto"}
function seasonPhase(state){const d=n(state?.season?.day),t=n(state?.season?.total_days);if(d===null||t===null||t<=0)return "unknown";const r=d/t;return r<.34?"early":r<.78?"mid":"late"}
function inferObjective(state,explicit){if(explicit&&explicit!=="auto")return {value:explicit,source:"explicit",certainty:"certain"};const focus=txt(state?.season?.focus),profession=txt(state?.season?.profession),vs=state?.vs||{};if(/pvp|siege|attack|combat|war|garrison|defen/.test(`${focus} ${profession}`))return {value:"pvp",source:"season_focus",certainty:"probable"};if(/pve|monster|campaign|zombie|boss|explor|progress/.test(`${focus} ${profession}`))return {value:"pve",source:"season_focus",certainty:"probable"};if(Number(vs?.day)>=1&&Number(vs?.day)<=6&&(vs?.opponent||vs?.week))return {value:"vs",source:"vs_context",certainty:"probable"};if(Number(state?.season?.number)>0)return {value:"season",source:"season_context",certainty:"speculative"};return {value:"balanced",source:"default",certainty:"speculative"}}
function knownTech(tech={}){return ["type_mastery_pct","hero_tech_pct","siege_to_seize_pct","defensive_fortification_pct","tactical_weapon_pct"].map(k=>({key:k,value:n(tech?.[k])})).filter(x=>x.value!==null)}
export function buildAdaptiveContext(state,{mainType=null,formationBonusPct=0,locale="en-GB"}={}){
  const pc=state?.player_context||{},explicitObjective=normalizeObjective(pc.objective),objective=inferObjective(state,explicitObjective),rawAge=n(pc.account_age_days),accountAge=rawAge!==null&&rawAge>=0?Math.min(5000,Math.round(rawAge)):null,serverProfile=normalizeServerProfile(pc.server_profile),tech=knownTech(state?.technology||{}),season=state?.season||{},vs=state?.vs||{},drone=state?.drone||{};
  const known=[objective.source!=="default",accountAge!==null,serverProfile!=="auto",Number(season?.number)>0,Number(vs?.day)>=1&&Number(vs?.day)<=6,tech.length>0,n(drone?.level)!==null||n(drone?.power_m)!==null,Boolean(mainType)].filter(Boolean).length;
  const confidence=clamp(38+known*7+(objective.source==="explicit"?8:0)+(pc.updated_at?4:0),35,94);
  return {generated_at:new Date().toISOString(),locale,objective:objective.value,objective_source:objective.source,objective_certainty:objective.certainty,account_age_days:accountAge,server_profile:serverProfile,season:{number:n(season?.number),day:n(season?.day),total_days:n(season?.total_days),phase:seasonPhase(state),focus:season?.focus||null,profession:season?.profession||null},vs:{week:n(vs?.week),day:n(vs?.day),opponent:vs?.opponent||null},composition:{main_type:mainType||null,formation_bonus_pct:n(formationBonusPct)},drone:{level:n(drone?.level),power_m:n(drone?.power_m)},technology:{known_count:tech.length,values:tech},confidence,source:"warboost_saved_context+scans+vs+season"};
}
function objectiveAdjustment(kind,ctx){const o=ctx?.objective||"balanced";const table={
  pvp:{exclusive:7,awakening:7,gear:6,technology:7,stars:5,level:3,drone:2,scan:0},
  vs:{exclusive:6,awakening:5,gear:5,technology:7,stars:5,level:4,drone:4,scan:0},
  pve:{drone:7,level:5,gear:4,stars:4,technology:4,exclusive:3,awakening:3,scan:0},
  season:{awakening:9,exclusive:6,technology:7,stars:4,gear:3,drone:3,level:2,scan:0},
  balanced:{exclusive:2,awakening:2,gear:2,technology:2,stars:2,level:2,drone:2,scan:0}
 };return table[o]?.[kind]??0}
function ageAdjustment(kind,ctx){const d=n(ctx?.account_age_days);if(d===null)return 0;if(d<60)return ["level","stars","drone"].includes(kind)?4:kind==="awakening"?-7:0;if(d>180)return ["exclusive","awakening","technology"].includes(kind)?4:kind==="level"?-2:0;return 0}
function serverAdjustment(kind,ctx){const s=ctx?.server_profile;if(s==="competitive")return ["exclusive","awakening","gear","technology"].includes(kind)?4:0;if(s==="new")return ["level","stars","drone"].includes(kind)?3:0;return 0}
function certaintyFor(x,ctx){if(x?.kind==="scan")return "certain";if(x?.data_freshness?.status==="stale"||x?.data_freshness?.status==="unknown")return "speculative";const direct=Number.isFinite(Number(x?.current))||Number.isFinite(Number(x?.impact_score));const evidence=(x?.evidence_ids||[]).length;if(direct&&evidence>=2&&ctx?.confidence>=70)return "certain";if(direct&&ctx?.confidence>=52)return "probable";return "speculative"}
function conditionKey(x){if(x?.data_freshness?.blocks_paid)return "refresh";const s=x?.timing_window?.status;return s==="spend_now"||s==="now"?"now":s==="hold_if_vs_priority"?"hold_vs":s==="check_payback"?"payback":"neutral"}
export function applyAdaptiveScoring(candidates,ctx){return (Array.isArray(candidates)?candidates:[]).map(x=>{const adjust=objectiveAdjustment(x.kind,ctx)+ageAdjustment(x.kind,ctx)+serverAdjustment(x.kind,ctx);const base=(Number(x.severity)||0)*.52+(Number(x.roi_score)||0)*.28+(Number(x.impact_score)||0)*.20;const marginal=clamp(base+adjust,1,100);return {...x,context_adjustment:adjust,marginal_value_score:marginal,certainty:certaintyFor(x,ctx),condition_key:conditionKey(x),calculated_at:ctx?.generated_at||new Date().toISOString()}})}
const TECH_LABEL={
  type_mastery_pct:"Type Mastery",hero_tech_pct:"Hero Tech",siege_to_seize_pct:"Siege to Seize",defensive_fortification_pct:"Defensive Fortification",tactical_weapon_pct:"Tactical Weapon"
};
function techLane(ctx,values){if(!values?.length)return null;const o=ctx?.objective;const preferred=o==="pvp"||o==="vs"?["siege_to_seize_pct","tactical_weapon_pct","type_mastery_pct","hero_tech_pct"]:o==="pve"?["hero_tech_pct","type_mastery_pct","tactical_weapon_pct"]:o==="season"?["type_mastery_pct","hero_tech_pct","siege_to_seize_pct","defensive_fortification_pct"]:["type_mastery_pct","hero_tech_pct","tactical_weapon_pct","siege_to_seize_pct","defensive_fortification_pct"];
  const incomplete=values.filter(x=>Number(x.value)<100);if(!incomplete.length)return null;
  // Pick the best current technology bottleneck, not merely the first known lane: gap drives value while objective relevance breaks close calls.
  return incomplete.map(x=>{const idx=preferred.indexOf(x.key),relevance=idx<0?0:(preferred.length-idx)*4,gap=Math.max(0,100-Number(x.value));return {x,score:gap+relevance}}).sort((a,b)=>b.score-a.score||a.x.value-b.x.value)[0]?.x||null}
export function technologyOpportunity(state,ctx){const values=ctx?.technology?.values||[];const lane=techLane(ctx,values);if(!lane)return null;const pct=Math.max(0,Math.min(100,lane.value));if(pct>=100)return null;const gap=100-pct;const impact=clamp(48+gap*.42+(ctx?.objective==="pvp"||ctx?.objective==="vs"?5:0),45,92);const cost=Math.max(.75,1.2-gap/180);return {lane:lane.key,label:TECH_LABEL[lane.key]||lane.key,pct,impact,cost,current_label:`${Math.round(pct)}%`,next_target:null,source_updated_at:state?.technology?.updated_at||null}}
