function fmt(v,locale){const n=Number(v);return Number.isFinite(n)?`${n.toLocaleString(locale,{maximumFractionDigits:2})} M`:"—"}
const L={
 fr:{player:(q,l)=>q?`Priorise ${q.name||"ton escouade principale"} (${fmt(q.power,l)}). Compare ensuite héros, étoiles, armes exclusives, équipements et Drone avant de dépenser.`:"Scanne au moins une escouade pour obtenir une priorité personnalisée.",alliance:n=>n?`Utilise les ${Math.min(5,n)} joueurs les plus puissants comme noyau de rally. Répartis ensuite défense, groupe mobile et réserves selon la progression du roster.`:"Fais rejoindre les membres avec l'invitation WarBoost pour créer un plan fiable.",vs:s=>s.opponent?`Jour ${s.day||"—"} contre ${s.opponent} : concentre les ressources sur les actions qui marquent aujourd'hui et conserve le reste pour les jours suivants.`:"WarBoost connaît le jour serveur mais attend encore l'adversaire VS.",season:s=>s.day?`Jour ${s.day} : sécurise d'abord les améliorations saisonnières qui débloquent la prochaine étape. Profession : ${s.profession||"—"}.`:"Scanne ou synchronise la saison pour recevoir un conseil adapté."},
 en:{player:(q,l)=>q?`Prioritize ${q.name||"your main squad"} (${fmt(q.power,l)}). Then compare heroes, stars, exclusive weapons, gear and Drone before spending.`:"Scan at least one squad to get a personalized priority.",alliance:n=>n?`Use the ${Math.min(5,n)} strongest players as the rally core, then split defense, mobile group and reserves from the roster progression.`:"Invite members with WarBoost before generating a reliable war plan.",vs:s=>s.opponent?`Day ${s.day||"—"} vs ${s.opponent}: spend only on actions that score today and keep the rest for later days.`:"WarBoost knows the server day but is still waiting for the VS opponent.",season:s=>s.day?`Day ${s.day}: secure the season upgrades that unlock your next step first. Profession: ${s.profession||"—"}.`:"Scan or synchronize the season for day-specific advice."},
 es:{player:(q,l)=>q?`Prioriza ${q.name||"tu escuadrón principal"} (${fmt(q.power,l)}). Compara héroes, estrellas, armas exclusivas, equipo y Dron antes de gastar.`:"Escanea al menos un escuadrón para obtener una prioridad personalizada.",alliance:n=>n?`Usa a los ${Math.min(5,n)} jugadores más fuertes como núcleo de rally y separa defensa, grupo móvil y reservas.`:"Invita miembros con WarBoost antes de generar un plan fiable.",vs:s=>s.opponent?`Día ${s.day||"—"} contra ${s.opponent}: gasta solo en acciones que puntúan hoy.`:"WarBoost conoce el día del servidor pero aún espera el rival VS.",season:s=>s.day?`Día ${s.day}: prioriza las mejoras de temporada que desbloquean tu siguiente paso.`:"Escanea o sincroniza la temporada para recibir un consejo adaptado."},
 de:{player:(q,l)=>q?`Priorisiere ${q.name||"deinen Haupttrupp"} (${fmt(q.power,l)}). Vergleiche danach Helden, Sterne, Exklusivwaffen, Ausrüstung und Drohne.`:"Scanne mindestens einen Trupp für eine persönliche Priorität.",alliance:n=>n?`Nutze die ${Math.min(5,n)} stärksten Spieler als Rally-Kern und teile danach Verteidigung, mobile Gruppe und Reserve.`:"Lade Mitglieder über WarBoost ein, bevor du einen Kriegsplan erstellst.",vs:s=>s.opponent?`Tag ${s.day||"—"} gegen ${s.opponent}: Ressourcen nur für heutige Punkte ausgeben.`:"WarBoost kennt den Servertag, wartet aber noch auf den VS-Gegner.",season:s=>s.day?`Tag ${s.day}: priorisiere Saison-Upgrades, die den nächsten Schritt freischalten.`:"Scanne oder synchronisiere die Saison für passende Ratschläge."},
 ja:{player:(q,l)=>q?`${q.name||"主力部隊"}（${fmt(q.power,l)}）を優先。英雄、星、専用武器、装備、ドローンを比較してから資源を使いましょう。`:"少なくとも1部隊をスキャンしてください。",alliance:n=>n?`上位${Math.min(5,n)}人をラリー中核にし、防衛・機動・予備に分けます。`:"WarBoost招待でメンバーを参加させてください。",vs:s=>s.opponent?`${s.opponent}との${s.day||"—"}日目：今日得点できる行動に資源を集中。`:"VS相手の同期を待っています。",season:s=>s.day?`${s.day}日目：次の段階を解放するシーズン強化を優先。`:"シーズンをスキャンまたは同期してください。"},
 zh:{player:(q,l)=>q?`优先提升 ${q.name||"主力队伍"}（${fmt(q.power,l)}）。花资源前比较英雄、星级、专武、装备和无人机。`:"至少扫描一支队伍以获得个性化优先级。",alliance:n=>n?`将最强的${Math.min(5,n)}名玩家作为集结核心，再分配防守、机动与预备组。`:"先通过 WarBoost 邀请成员加入。",vs:s=>s.opponent?`第${s.day||"—"}天对阵 ${s.opponent}：只把资源投入今天能得分的项目。`:"WarBoost 已知道服务器日期，但仍在等待 VS 对手。",season:s=>s.day?`第${s.day}天：优先完成能解锁下一阶段的赛季强化。`:"扫描或同步赛季以获得对应建议。"},
 ar:{player:(q,l)=>q?`أعطِ الأولوية لـ ${q.name||"فريقك الرئيسي"} (${fmt(q.power,l)}). قارن الأبطال والنجوم والأسلحة الحصرية والمعدات والدرون قبل الإنفاق.`:"امسح فريقاً واحداً على الأقل للحصول على أولوية مخصصة.",alliance:n=>n?`استخدم أقوى ${Math.min(5,n)} لاعبين كنواة للرالي، ثم وزّع الدفاع والمجموعة المتحركة والاحتياط.`:"ادعُ الأعضاء عبر WarBoost قبل إنشاء خطة حرب موثوقة.",vs:s=>s.opponent?`اليوم ${s.day||"—"} ضد ${s.opponent}: أنفق فقط على الأنشطة التي تسجل نقاطاً اليوم.`:"WarBoost يعرف يوم الخادم لكنه ينتظر خصم VS.",season:s=>s.day?`اليوم ${s.day}: أعطِ الأولوية لترقيات الموسم التي تفتح الخطوة التالية.`:"امسح أو زامن الموسم للحصول على نصيحة مناسبة."}
};
function pack(locale){const x=String(locale||"en").toLowerCase();if(x.startsWith("fr"))return L.fr;if(x.startsWith("es"))return L.es;if(x.startsWith("de"))return L.de;if(x.startsWith("ja"))return L.ja;if(x.startsWith("zh"))return L.zh;if(x.startsWith("ar"))return L.ar;return L.en}
function intl(locale){return ({fr:"fr-FR",es:"es-ES",de:"de-DE",ja:"ja-JP",zh:"zh-CN",ar:"ar-SA"})[String(locale||"").split("-")[0]]||"en-GB"}
export default function handler(req,res){if(req.method!=="POST")return res.status(405).json({error:"method_not_allowed"});const scope=String(req.body?.scope||"player"),s=req.body?.state||{},p=pack(req.body?.locale),loc=intl(req.body?.locale);let advice;if(scope==="player"){const q=(s.squads||[]).filter(x=>Number(x?.power)>0).sort((a,b)=>Number(b.power)-Number(a.power))[0];advice=p.player(q,loc)}else if(scope==="alliance")advice=p.alliance((s.alliance?.members||[]).length);else if(scope==="vs")advice=p.vs(s.vs||{});else advice=p.season(s.season||{});return res.status(200).json({ok:true,engine:"warboost-rules-v1.2",advice})}
