import {requireUser} from "../lib/auth.js";
function env(n){return String(process.env[n]||"").trim()}
function textFromResponse(j){if(typeof j?.output_text==="string")return j.output_text;for(const item of j?.output||[])for(const c of item?.content||[])if(typeof c?.text==="string")return c.text;return ""}
function jsonFromText(text){const s=String(text||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/```$/,"" ).trim();return JSON.parse(s)}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function str(v,max=120){const s=String(v??"").trim();return s?s.slice(0,max):null}
function sanitize(extracted,now,scanType){const out={};const forcedSquad=String(scanType||"").match(/^squad([1-4])$/i);const forcedSquadId=forcedSquad?Number(forcedSquad[1]):null;
  if(extracted?.player){const p={};for(const k of ["name","server_id","coordinates","role"]){const v=str(extracted.player[k],80);if(v)p[k]=v}for(const k of ["hq_level","power_m"]){const v=num(extracted.player[k]);if(v!==null)p[k]=v}if(Object.keys(p).length)out.player=p}
  if(extracted?.drone){const d={updated_at:now};for(const k of ["level","power_m"]){const v=num(extracted.drone[k]);if(v!==null)d[k]=v}if(Object.keys(d).length>1)out.drone=d}
  if(Array.isArray(extracted?.squads)){const arr=Array(4).fill(null);const source=forcedSquadId?extracted.squads.slice(0,1):extracted.squads.slice(0,4);for(const q of source){const id=forcedSquadId||Math.max(1,Math.min(4,Number(q?.id)||1)),x={id,updated_at:now};const name=str(q?.name,40);if(name)x.name=name;const power=num(q?.power);if(power!==null)x.power=power;if(Array.isArray(q?.heroes)){x.heroes=Array(5).fill(null);q.heroes.slice(0,5).forEach((h,idx)=>{const hx={};const hn=str(h?.name,50);if(hn)hx.name=hn;for(const k of ["level","stars","power"]){const v=num(h?.[k]);if(v!==null)hx[k]=v}for(const k of ["exclusive","gear"]){const v=str(h?.[k],100);if(v)hx[k]=v}x.heroes[idx]=hx})}arr[id-1]=x}out.squads=arr}
  if(extracted?.alliance){const a={updated_at:now};for(const k of ["tag","name","role"]){const v=str(extracted.alliance[k],80);if(v)a[k]=k==="tag"?v.toUpperCase():v}if(Object.keys(a).length>1)out.alliance=a}
  if(extracted?.vs){const v={updated_at:now};for(const k of ["week","day"]){const n=num(extracted.vs[k]);if(n!==null)v[k]=n}for(const k of ["opponent","our_alliance"]){const x=str(extracted.vs[k],60);if(x)v[k]=x.toUpperCase()}for(const k of ["our_score","their_score"]){if(extracted.vs[k]!==undefined&&extracted.vs[k]!==null)v[k]=extracted.vs[k]}if(Object.keys(v).length>1)out.vs=v}
  if(extracted?.season){const s={updated_at:now};for(const k of ["name","profession"]){const v=str(extracted.season[k],80);if(v)s[k]=v}for(const k of ["number","day","total_days","progress_pct","resistance"]){const v=num(extracted.season[k]);if(v!==null)s[k]=v}if(Object.keys(s).length>1)out.season=s}
  return out}
async function customVision(payload){const url=env("WARBOOST_VISION_ENDPOINT");if(!url)return null;const secret=env("WARBOOST_VISION_SECRET"),r=await fetch(url,{method:"POST",headers:{"content-type":"application/json",...(secret?{"x-warboost-vision-secret":secret}:{})},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||`Vision HTTP ${r.status}`);return j.state||j.data||j}
async function openaiVision({image,scanType,locale}){const key=env("OPENAI_API_KEY");if(!key)return null;const model=env("WARBOOST_VISION_MODEL")||"gpt-5.6-luna";const forced=String(scanType||"").match(/^squad([1-4])$/i);const slotRule=forced?` This screenshot must be stored as Squad ${forced[1]}. Return at most one squad object and force its id to ${forced[1]}, even if the screenshot itself does not visibly show the squad number.`:"";const prompt=`You are WarBoost Vision. Extract only information visibly present in this Last War mobile-game screenshot. Screenshot type: ${scanType}. User locale: ${locale}.${slotRule} Never guess missing values. Return JSON only, no markdown. Allowed shape: {"player":{"name":string,"server_id":string,"hq_level":number,"power_m":number,"coordinates":string,"role":string},"drone":{"level":number,"power_m":number},"squads":[{"id":1-4,"name":string,"power":number,"heroes":[{"name":string,"level":number,"stars":number,"power":number,"exclusive":string,"gear":string}]}],"alliance":{"tag":string,"name":string,"role":string},"vs":{"week":number,"day":number,"our_alliance":string,"opponent":string,"our_score":number,"their_score":number},"season":{"name":string,"number":number,"day":number,"total_days":number,"profession":string,"progress_pct":number,"resistance":number}}. Omit fields that are not clearly visible. Power values should be numeric millions when the screen uses M (for example 42.17M -> 42.17).`;
  const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model,input:[{role:"user",content:[{type:"input_text",text:prompt},{type:"input_image",image_url:image}]}]})}),j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j?.error?.message||`Vision HTTP ${r.status}`),{status:r.status});return jsonFromText(textFromResponse(j))}
export default async function handler(req,res){res.setHeader("Cache-Control","no-store");if(req.method!=="POST")return res.status(405).json({error:"method_not_allowed"});try{await requireUser(req);const image=String(req.body?.image_data_url||""),scanType=String(req.body?.scan_type||"profile"),locale=String(req.body?.locale||"en");if(!/^data:image\/(jpeg|jpg|png|webp);base64,/i.test(image))return res.status(400).json({error:"invalid_image",message:"Invalid image"});if(image.length>4_200_000)return res.status(413).json({error:"image_too_large",message:"Image too large"});let extracted=await customVision({image_data_url:image,scan_type:scanType,locale});let engine="custom";if(!extracted){extracted=await openaiVision({image,scanType,locale});engine="openai"}if(!extracted)return res.status(503).json({error:"scan_not_configured",code:"SCAN_NOT_CONFIGURED",message:"WarBoost Vision is not configured"});const now=new Date().toISOString(),state=sanitize(extracted,now,scanType);return res.status(200).json({ok:true,engine,scanned_at:now,state})}catch(e){console.error("WarBoost scan",{message:e?.message,status:e?.status});return res.status(e?.status||500).json({error:"scan_failed",message:e?.message||"Scan failed"})}}
